### ISSUE TITLE
Error when update Z-Wave JS from  0.1.48 to  0.1.49

### ISSUE THREAD

**Issue by shaddow11** [home-assistant/addons#2280] opened 2021-11-23 10:50 UTC
### Describe the issue you are experiencing

When trying to update Z-Wave JS i've got errors few times:

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Z-Wave JS

### What is the version of the add-on?

0.1.48

### Steps to reproduce the issue

1. Supervisor Menu
2. Click on Z-Wave JS
3. Click on Update
4. Backup is checked
5. After a few seconds the error pops up.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:109
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 12:40:23 PM (2 occurrences)
Last logged: 12:41:58 PM

Failed to to call /store/addons/core_zwave_js/update - Can't install homeassistant/aarch64-addon-zwave_js:0.1.49: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.1.49&fromImage=homeassistant%2Faarch64-addon-zwave_js: Not Found ("manifest for homeassistant/aarch64-addon-zwave_js:0.1.49 not found: manifest unknown: manifest unknown")
```

### Anything in the add-on logs that might be useful for us?

```txt
No errors on add-on logs
```

**Comment by MartinHjelmare** [comment] 2021-11-23 11:15
Thanks for the report! We're investigating.

**Comment by PerfectCrime** [comment] 2021-11-23 12:59
Same issue here

**Comment by MartinHjelmare** [comment] 2021-11-23 13:02
Please don't post "same issue" and similar replies. Every new post sends a notification to all people subscribed to the issue. The appropriate way of showing that you're affected by the issue is by reacting with 👍 to the top post.

We're aware of the issue and working on solving it. Thanks!

**Comment by matswi** [comment] 2021-11-23 13:38
I'm not sure how this is installed but there doesn't seem to be any 0.1.49 image on dockerhub.
https://hub.docker.com/r/homeassistant/amd64-addon-zwave_js/tags

**Comment by bubba9891** [comment] 2021-11-23 14:16
Same issue here.

**Comment by canedje** [comment] 2021-11-23 19:44
same here:
![image](https://user-images.githubusercontent.com/23150947/143092880-3019483d-804d-462f-8b67-c3907adc8c92.png)

**Comment by blarsen65** [comment] 2021-11-23 23:25
When installing a fresh HA on a PI4, this is the message:
Can't install homeassistant/aarch64-addon-zwave_js:0.1.49: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.1.49&fromImage=homeassistant%2Faarch64-addon-zwave_js: Not Found ("manifest for homeassistant/aarch64-addon-zwave_js:0.1.49 not found: manifest unknown: manifest unknown")

**Comment by kksligh** [comment] 2021-11-24 00:46
Same issue here

**Comment by sihartley** [comment] 2021-11-24 04:12
I am also having this exact same issue. Glad this isn't just me!! (Means I haven't screwed something up for a change!) :-)

**Comment by MartinHjelmare** [comment] 2021-11-24 04:13
Please don't post a comment if you have no new information to provide.

We're working on fixing this so we don't need more information at the moment. Thanks!

**Comment by jatgm1** [comment] 2021-11-24 05:25
Can confirm a problem. Odroid n2+ stock home assistant is fully updated, stable version.

**Comment by cipmd** [comment] 2021-11-24 05:29
Appears not to be just an issue with an update but also with a fresh install.  

21-11-23 21:28:20 ERROR (SyncWorker_1) [supervisor.docker.interface] Can't install homeassistant/aarch64-addon-zwave_js:0.1.49: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.1.49&fromImage=homeassistant%2Faarch64-addon-zwave_js: Not Found ("manifest for homeassistant/aarch64-addon-zwave_js:0.1.49 not found: manifest unknown: manifest unknown")

**Comment by MartinHjelmare** [comment] 2021-11-24 10:07
We've merged a temporary fix that rolls back the add-on to the image for version 0.1.48. This should allow new users to install 0.1.48 and existing users won't try to update to the missing image for 0.1.49.

I'll update here again when we have solved the deployment issues so we can release the update planned for 0.1.49. Thanks for your patience.

**Comment by johandijkstra** [comment] 2021-11-24 10:57
![image](https://user-images.githubusercontent.com/60472692/143225798-de8c3a36-aa75-4745-ab17-1f28fbb032f5.png)

huh? :)

**Comment by MartinHjelmare** [comment] 2021-11-24 12:19
We finished the deployment work and re-released 0.1.49.

Again, thanks for your patience. :+1: 

I'll close here. Let us know if there are any issues with installing 0.1.49.

**Closed by MartinHjelmare** 2021-11-24 12:19 UTC
Labels: add-on: zwave_js

**Comment by los93sol** [comment] 2021-11-24 13:53
@MartinHjelmare It looks like this may be impacting more than just ZWaveJS, I had that issue yesterday, but now a LetsEncrypt update has popped up and it is exhibiting the same issue.

Can't install homeassistant/aarch64-addon-letsencrypt:4.12.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=4.12.0&fromImage=homeassistant%2Faarch64-addon-letsencrypt: Not Found ("manifest for homeassistant/aarch64-addon-letsencrypt:4.12.0 not found: manifest unknown: manifest unknown")

**Comment by MartinHjelmare** [comment] 2021-11-24 17:11
Please open a separate issue for that if it's still a problem.

**Comment by markblinkhorn** [comment] 2021-11-26 16:10
Restored back to version 1.48 due to z-wave not updating Lovelace with requested state changes (manual or automation) from Eurotronics Spirit TRVs (and possibly other devices). Message 'Poll canceled because the value was updated' appears in log in response to state change command. Command *IS* carried out, but Lovelace never gets told. Version 1.48 does not have this issue.

**Comment by MartinHjelmare** [comment] 2021-11-26 16:30
We're aware and there's already an issue for this in the core repo.

**Comment by eddriesen** [comment] 2021-11-29 17:56
> Restored back to version 1.48 due to z-wave not updating Lovelace with requested state changes (manual or automation) from Eurotronics Spirit TRVs (and possibly other devices). Message 'Poll canceled because the value was updated' appears in log in response to state change command. Command _IS_ carried out, but Lovelace never gets told. Version 1.48 does not have this issue.
> 
> I am aware this is a new issue. You want I should open a new case?

I was affected with this in 0.1.49, so I rolled back to 0.1.48. Now I bought a steinel xled 2 zwave and it wasn't including properly.

I get does not support command class version, but device is listed in database.

Since my zwave network was janky, I removed this device again. HOWEVER my exisiting steinel is140-2 got removed to ( without putting it in exclusion mode!). I'm totally flabbergasted!

Can I provide more data? I'm a bit loss for solutions and hope a next release 'll fix some stuff. Great work so far! Nothing's on fire here ;) .

**Comment by MartinHjelmare** [comment] 2021-11-29 18:01
Please open a new issue in the core repo of there isn't already an issue that matches your problem experience.

The issue here was just about a docker deployment issue and is resolved and closed. Thanks!
