### ISSUE TITLE
Failed to execute controller command after 1/3 attempts. Scheduling next try in 100 ms

### ISSUE THREAD

**Issue by sanderlv** [home-assistant/addons#2298] opened 2021-12-09 10:35 UTC
### Describe the issue you are experiencing

I have continuous and loads of "Failed to execute controller command after 1/3 attempts. Scheduling next try in 100 ms."

I do not see any issues in the function of my zwave network. Now and then I have some delays but not really serious.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Z-Wave JS

### What is the version of the add-on?

0.1.50

### Steps to reproduce the issue

I have home assistant running in vmware esxi for about 2 years now. First with OZW (Beta) and now with ZwaveJS addon.
The log always shows every few minutes:
```
2021-12-09T09:23:55.910Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try in 100 ms.
```

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

### Anything in the add-on logs that might be useful for us?

```txt
2021-12-09T09:23:55.910Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T09:25:55.404Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T09:28:55.208Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T09:32:55.482Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T09:34:55.531Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T09:35:05.707Z CNTRLR   [Node 065] Timed out while waiting for a response from the node (ZW0201)
2021-12-09T09:35:05.780Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T09:36:55.321Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T09:38:55.770Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T09:41:55.317Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T09:41:55.505Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T09:43:55.288Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T09:43:55.624Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T09:44:55.188Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T09:44:55.553Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T09:45:55.905Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T09:50:55.253Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T09:50:55.859Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T09:51:55.271Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T09:53:05.700Z CNTRLR   [Node 076] Timed out while waiting for a response from the node (ZW0201)
2021-12-09T09:54:55.330Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T09:56:55.214Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T09:56:58.192Z CNTRLR « [Node 057] received wakeup notification
2021-12-09T09:56:58.193Z CNTRLR   [Node 057] The node is now awake.
2021-12-09T09:56:59.194Z CNTRLR » [Node 057] Sending node back to sleep...
2021-12-09T09:56:59.255Z CNTRLR   [Node 057] The node is now asleep.
2021-12-09T09:57:55.597Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T09:57:55.986Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T09:59:11.519Z CNTRLR « [Node 021] received wakeup notification
2021-12-09T09:59:11.519Z CNTRLR   [Node 021] The node is now awake.
2021-12-09T09:59:11.575Z CNTRLR « [Node 021] received wakeup notification
2021-12-09T09:59:12.577Z CNTRLR » [Node 021] Sending node back to sleep...
2021-12-09T09:59:12.634Z CNTRLR   [Node 021] The node is now asleep.
2021-12-09T09:59:55.363Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T10:01:54.654Z CNTRLR « [Node 012] received wakeup notification
2021-12-09T10:03:55.237Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T10:04:55.468Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T10:06:55.292Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T10:07:55.348Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T10:08:55.224Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T10:09:55.535Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T10:10:55.449Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-09T10:15:55.287Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
```

### Additional information

I also asked in the forum:
https://community.home-assistant.io/t/zwavejs-is-this-normal-failed-to-execute-controller-command-after-1-3-attempts-scheduling-next-try-in-100-ms

**Comment by sanderlv** [comment] 2021-12-11 08:33
Added logging (after a heal of around 3 hours which is stopped 15-30 mins.
[zwavejs log.txt](https://github.com/home-assistant/addons/files/7696682/zwavejs.log.txt)

**Comment by sanderlv** [comment] 2021-12-11 17:55
Another set of logging
[zwavejs log.txt](https://github.com/home-assistant/addons/files/7697496/zwavejs.log.txt)

**Comment by MartinHjelmare** [comment] 2021-12-11 18:11
Duplicate of https://github.com/home-assistant/core/issues/61502

**Closed by MartinHjelmare** 2021-12-11 18:11 UTC

**Comment by sanderlv** [comment] 2021-12-11 18:49
Here you go...
[zwavejs log.txt](https://github.com/home-assistant/addons/files/7697568/zwavejs.log.txt)
[zwave_js_dump.zip](https://github.com/home-assistant/addons/files/7697571/zwave_js_dump.zip)
