### ISSUE TITLE
Failed to start add-on 0.1.60

### ISSUE THREAD

**Issue by odechr** [home-assistant/addons#2498] opened 2022-05-25 06:36 UTC
### Describe the issue you are experiencing

After upgrading from 0.1.59 too 0.1.60 i get this:

Failed to start add-on
Image homeassistant/amd64-addon-zwave_js:0.1.60 does not exist for addon_core_zwave_js

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Z-Wave JS

### What is the version of the add-on?

0.1.60

### Steps to reproduce the issue

Install 0.1.60

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:120
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 07:18:36 (4 occurrences)
Last logged: 08:33:26

Failed to to call /addons/core_zwave_js/start - Image homeassistant/amd64-addon-zwave_js:0.1.60 does not exist for addon_core_zwave_js

-----------------------------------------------------------------------------------------

Logger: homeassistant.components.zwave_js
Source: components/zwave_js/addon.py:372
Integration: Z-Wave JS (documentation, issues)
First occurred: 06:40:29 (94 occurrences)
Last logged: 08:35:20

Failed to start the Z-Wave JS add-on: Image homeassistant/amd64-addon-zwave_js:0.1.60 does not exist for addon_core_zwave_js
```

**Comment by dhover** [comment] 2022-05-25 07:09
I get the same error. Normally the update is very simple. Just pressing the install button and the update is ready. Now an error occurs. Maybe this log helps:

```
2022-05-25 09:03:51 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140098655783232] Error updating Z-Wave JS: Can't install homeassistant/amd64-addon-zwave_js:0.1.60: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=0.1.60&fromImage=homeassistant%2Famd64-addon-zwave_js&platform=linux%2Famd64: Internal Server Error ("Head "https://registry-1.docker.io/v2/homeassistant/amd64-addon-zwave_js/manifests/0.1.60": Get "https://auth.docker.io/token?scope=repository%3Ahomeassistant%2Famd64-addon-zwave_js%3Apull&service=registry.docker.io": dial tcp: lookup auth.docker.io: no such host")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 47, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install homeassistant/amd64-addon-zwave_js:0.1.60: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=0.1.60&fromImage=homeassistant%2Famd64-addon-zwave_js&platform=linux%2Famd64: Internal Server Error ("Head "https://registry-1.docker.io/v2/homeassistant/amd64-addon-zwave_js/manifests/0.1.60": Get "https://auth.docker.io/token?scope=repository%3Ahomeassistant%2Famd64-addon-zwave_js%3Apull&service=registry.docker.io": dial tcp: lookup auth.docker.io: no such host")
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 189, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 152, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 411, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Z-Wave JS: Can't install homeassistant/amd64-addon-zwave_js:0.1.60: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=0.1.60&fromImage=homeassistant%2Famd64-addon-zwave_js&platform=linux%2Famd64: Internal Server Error ("Head "https://registry-1.docker.io/v2/homeassistant/amd64-addon-zwave_js/manifests/0.1.60": Get "https://auth.docker.io/token?scope=repository%3Ahomeassistant%2Famd64-addon-zwave_js%3Apull&service=registry.docker.io": dial tcp: lookup auth.docker.io: no such host")

```

**Comment by Lvecsei** [comment] 2022-05-25 11:26
I get the same error as well. This is my first post here so I apologize if I'm doing things wrong:

Logger: homeassistant.components.zwave_js
Source: components/zwave_js/addon.py:372
Integration: Z-Wave JS (documentation, issues)
First occurred: May 24, 2022, 22:24:06 (410 occurrences)
Last logged: 07:23:34

Failed to start the Z-Wave JS add-on: Image homeassistant/aarch64-addon-zwave_js:0.1.60 does not exist for addon_core_zwave_js

**Comment by selzilla** [comment] 2022-05-25 13:15
The identical error for me too

**Comment by raman325** [comment] 2022-05-25 15:32
another thing you should try is rebooting your HA system before the installation/start. There are reports that in some cases users who ran 0.1.59 and hit the other issue needed a full reboot to get 1.60 to start

**Comment by raman325** [comment] 2022-05-25 15:32
> Oki i can try that. Will i loose my entity ID etc? Im bad at taking backup on just addon updates. I do full backup at 4 am each day. So it is possible to roll back the whole system.

No, do not remove the config entry from your HA installation, just the addon. Please do remember to save your addon configuration though before you uninstall, you will need to use the same security keys in order to continue talking to your devices

**Comment by Lvecsei** [comment] 2022-05-26 00:37
I reverted to a backup of 0.1.58, rebooted, updated to 0.1.60, and my system is working again - makes sense, if this is a 0.1.59 >> 0.1.60 update issue.

**Comment by raman325** [comment] 2022-05-26 01:50
it was not a 0.1.59 to 0.1.60 issue, it was an issue with the 0.1.59 build. To be honest, I can't explain why you experienced this strange behavior but glad you got it resolved

**Comment by odechr** [comment] 2022-05-26 07:09
> > Oki i can try that. Will i loose my entity ID etc? Im bad at taking backup on just addon updates. I do full backup at 4 am each day. So it is possible to roll back the whole system.
> 
> No, do not remove the config entry from your HA installation, just the addon - your config entry will stop working because it can't connect, but once the addon is reinstalled (configured with the same security keys as before) and running, the config entry should connect again and all your existing entities will be used. Please do remember to save your addon configuration though before you uninstall, you will need to use the same security keys in order to continue talking to your devices

Copied the YAML config in the addon.
Uninstalled.
Reinstalled.
Reloaded the addon.

Works like a charm. Not sure if i should close the bug?

**Comment by dhover** [comment] 2022-05-27 09:12
Today I've updated to 0.1.60 without errors. I didn't change anything since I got errors a few days ago. So it seems the problem is being solved!

**Comment by MartinHjelmare** [comment] 2022-05-27 09:16
Closing here as affected users seem to no longer experience the issue.

**Closed by MartinHjelmare** 2022-05-27 09:16 UTC
Labels: add-on: zwave_js
