### ISSUE TITLE
Installing Let's Encrypt doesn't work

### ISSUE THREAD

**Issue by nando83** [home-assistant/addons#2287] opened 2021-11-24 13:25 UTC
### Describe the issue you are experiencing

I'm trying to install and have the next message:

No se pudo instalar el complemento
Can't install homeassistant/aarch64-addon-letsencrypt:4.12.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=4.12.0&fromImage=homeassistant%2Faarch64-addon-letsencrypt: Not Found ("manifest for homeassistant/aarch64-addon-letsencrypt:4.12.0 not found: manifest unknown: manifest unknown")

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

4.12.0

### Steps to reproduce the issue

Installing

### Anything in the Supervisor logs that might be useful for us?

```txt
21-11-24 14:15:51 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image homeassistant/aarch64-addon-letsencrypt with tag 4.12.0.
21-11-24 14:15:54 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install homeassistant/aarch64-addon-letsencrypt:4.12.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=4.12.0&fromImage=homeassistant%2Faarch64-addon-letsencrypt: Not Found ("manifest for homeassistant/aarch64-addon-letsencrypt:4.12.0 not found: manifest unknown: manifest unknown")
```

**Comment by serlinGi** [comment] 2021-11-24 14:44
also for me the same problem...
in attaching screenshots with error and description of my installation
Thx

![error_update](https://user-images.githubusercontent.com/63103970/143259332-2ce4f0ff-c382-4a41-b43d-e79875aaa8f7.PNG)
![MySystem](https://user-images.githubusercontent.com/63103970/143259358-6f56c65c-35d1-454e-99e0-25c4937a860f.PNG)

**Comment by VicenteKER** [comment] 2021-11-24 15:05
Same error here...

**Comment by mdegat01** [comment] 2021-11-24 16:23
Believe this is a duplicate of #2286 . Installing vs updating but same missing manifest error in the end.

**Comment by pickonedev** [comment] 2021-11-24 17:12
Same problem

**Comment by ludeeus** [comment] 2021-11-24 17:13
Duplicate of <https://github.com/home-assistant/addons/issues/2287>

**Closed by ludeeus** 2021-11-24 17:13 UTC
