### ISSUE TITLE
SSH addon fails to start as it can not write configuration to /data/addons/data/a0d7b954_ssh/options.json

### ISSUE THREAD

**Issue by jmartens** [home-assistant/addons#2066] opened 2021-06-09 05:01 UTC
## The problem

Fresh install and restored snapshot, after that updated all addons to latest version, now SSH addon fails to start

## Environment

- Add-on with the issue: SSH add on
- Add-on release with the issue: 8.2.3
- Last working add-on release (if known): 8.0.0 IIRC
- Operating environment (OS/Supervised): 

version | core-2021.6.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.10.42
arch | x86_64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.0
-- | --
update_channel | stable
supervisor_version | supervisor-2021.05.4
docker_version | 20.10.6
disk_total | 30.8 GB
disk_used | 4.5 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (1.18.0), Portainer (1.5.0), SSH & Web Terminal (8.2.3), Visual Studio Code (3.4.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

## Problem-relevant configuration

```yaml
ssh:
  username: root
  password: ''
  authorized_keys:
    - >-
      ssh-rsa
       **** REDACTED ****
  sftp: true
  compatibility_mode: false
  allow_agent_forwarding: false
  allow_remote_port_forwarding: false
  allow_tcp_forwarding: false
zsh: true
share_sessions: true
packages: []
init_commands: []

```

## Traceback/Error logs

From Supervisor logs:
```txt
21-06-09 04:54:43 ERROR (MainThread) [supervisor.utils.json] Can't write /data/addons/data/a0d7b954_ssh/options.json: [Errno 2] No such file or directory: '/data/addons/data/a0d7b954_ssh/tmpb73jm8ov'
21-06-09 04:54:43 ERROR (MainThread) [supervisor.addons.addon] Add-on a0d7b954_ssh can't write options
```

**Comment by jmartens** [comment] 2021-06-09 06:07
I noticed a similar report for another addon (DuckDNS) in #2051.

**Comment by jmartens** [comment] 2021-06-09 19:15
I logged into the docker supervisor container and listed the directory contents of the /data/addons/data folder to find out that there is no folder for the ssh addon:

```
bash-5.1# ls -la /data/addons/data/
total 20
drwxr-xr-x    5 root     root          4096 Jun  9 04:17 .
drwxr-xr-x    6 root     root          4096 Jun  9 03:23 ..
drwxr-xr-x    3 root     root          4096 Jun  9 04:05 a0d7b954_esphome
drwxr-xr-x    2 root     root          4096 Jun  9 03:53 a0d7b954_portainer
drwxr-xr-x    5 root     root          4096 Jun  9 04:48 a0d7b954_vscode
bash-5.1#
```

Not sure why? I manually created the folder and after that I was able to start the addon.

I think we need to find out why the folder was not created (automatically) upon installation of the addon where that seems to be done properly for other addons link portainer, esphome and vscode?

**Comment by ludeeus** [comment] 2021-06-12 07:49
This is indeed a duplicate of #2051
But it's not in the correct repository.

**Closed by ludeeus** 2021-06-12 07:49 UTC
Labels: add-on: ssh
