### ISSUE TITLE
Homematic OCCU Addon not starting since 11.0.0 update

### ISSUE THREAD

**Issue by J-Ha** [home-assistant/addons#1718] opened 2020-12-16 15:06 UTC
## The problem

The Homematic OCCU Addon is not starting since the 11.0.0 update.
10.3.0 was running well without any problems
## Environment

- Add-on with the issue: Homematic
- Add-on release with the issue: 11.0.0
- Last working add-on release (if known): 10.3.0 
- Operating environment (OS/Supervised): Home Assistant OS 5.8 with Supervisor 2020.12.7

## Problem-relevant configuration

```yaml
rf_enable: true
wired_enable: false
hmip_enable: false
rf:
  - type: CCU2
    device: /dev/ttyAMA0
wired:
  - serial: xy
    key: abc
    ip: 192.168.0.0
hmip:
  - type: HMIP_CCU2
    device: /dev/ttyUSB0
regahss_reset: false

```

## Traceback/Error logs

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] certs.sh: executing... 
Generating a RSA private key
....+++++
...............................................................+++++
writing new private key to '/etc/config/server.pem'
-----
[cont-init.d] certs.sh: exited 0.
[cont-init.d] env.sh: executing... 
[cont-init.d] env.sh: exited 0.
[cont-init.d] hm_ip.sh: executing... 
[cont-init.d] hm_ip.sh: exited 0.
[cont-init.d] hm_rfd.sh: executing... 
[16:05:37] INFO: Setup BidCos-RF
[16:05:38] INFO: RFd update was successful
[cont-init.d] hm_rfd.sh: exited 0.
[cont-init.d] hm_wired.sh: executing... 
[cont-init.d] hm_wired.sh: exited 0.
[cont-init.d] interface.sh: executing... 
[cont-init.d] interface.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:05:40] INFO: Initialize webinterface routing...
[15:05:40] INFO: Wait until HMServer is setup
2020-12-16 15:05:40: (plugin.c.195) dlopen() failed for: /usr/lib/lighttpd/mod_openssl.so /usr/lib/lighttpd/mod_openssl.so: cannot open shared object file: No such file or directory
2020-12-16 15:05:40: (server.c.1225) loading plugins finally failed
lighttpd-angel.c.148: child (pid=507) exited normally with exitcode: 255
[15:05:41] INFO: Starting rfd...
/opt/hm/bin/rfd: error while loading shared libraries: libelvutils.so: cannot open shared object file: No such file or directory
[15:05:41] INFO: Starting HMServer...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] hmip.sh: executing... 
[cont-finish.d] hmip.sh: exited 0.
[cont-finish.d] regahss.sh: executing... 
[cont-finish.d] regahss.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by J-Ha** [comment] 2020-12-16 15:22
Update:
with 11.0.1 the problem still exist:
```
[16:19:30] INFO: Initialize webinterface routing...
2020-12-16 16:19:30: (plugin.c.195) dlopen() failed for: /usr/lib/lighttpd/mod_openssl.so /usr/lib/lighttpd/mod_openssl.so: cannot open shared object file: No such file or directory
2020-12-16 16:19:30: (server.c.1225) loading plugins finally failed
lighttpd-angel.c.148: child (pid=1817) exited normally with exitcode: 255
```

**Comment by obfri** [comment] 2020-12-16 16:50
Same at my side with 11.0.0 with same logentries, couldn't check 11.0.1 because not visible.

**Comment by bedacht** [comment] 2020-12-17 06:29
The 11.0.4 update fixed that issue on my system.

**Comment by obfri** [comment] 2020-12-17 10:46
I can confirm that 11.0.4 solves problem 👍 :-)

**Comment by frenck** [comment] 2020-12-21 20:29
Since we have 2 reports of this casing being solved in the last update, I'm closing this issue. Thanks for reporting back 👍 

Happy Holidays 🎄

**Closed by frenck** 2020-12-21 20:29 UTC
Labels: add-on: homematic
