### ISSUE TITLE
MariaDB: Add-On Configuration page is broken in 2023.4.6/10.0

### ISSUE THREAD

**Issue by coltoncat** [home-assistant/addons#3003] opened 2023-04-24 11:57 UTC
### Describe the issue you are experiencing

The add-on configuration page is broken in 10.0 HA v 2023.4.6. You can only populate the "database" field, all other fields are not actually controls. Furthermore editing in YAML is also broken. 

<img width="1091" alt="Screenshot 2023-04-24 at 13 54 20" src="https://user-images.githubusercontent.com/1881504/233988802-fe242256-92a8-44e0-b96b-c87c2c3c973c.png">
<img width="1051" alt="Screenshot 2023-04-24 at 13 54 15" src="https://user-images.githubusercontent.com/1881504/233988812-83f16e91-5b20-4600-90ab-fabf5d1d15c0.png">

This is for a brand-new installation of the add-on.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

MariaDB

### What is the version of the add-on?

 2.5.2

### Steps to reproduce the issue

1. Brand new installation of HassOS. 
2. Install AddOn from Official add-on store. 
3. Navigate the configuration tab, broken configuration UI exists as described.

### System Health information

There are currently no repairs available

### Anything in the Supervisor logs that might be useful for us?

```txt
None.
```

### Anything in the add-on logs that might be useful for us?

```txt
No errors have been reported (MariaDB) - which makes sense as initial configuration cannot be completed.
```

**Comment by agners** [comment] 2023-04-24 15:26
Seems like a duplicate of #2970.

**Closed by agners** 2023-04-24 15:26 UTC
Labels: duplicate, add-on: mariadb
