### ISSUE TITLE
Schlage BE469 Not reporting manual lock status into Home Assistant with Zwave-JS

### ISSUE THREAD

**Issue by wotelljm** [home-assistant/addons#1812] opened 2021-02-06 15:09 UTC
## Environment

- Add-on with the issue: Zwave-JS
- Add-on release with the issue: 0.1.4
- Last working add-on release (if known):  N/A
- Operating environment (OS/Supervised): Home Assistant OS 5.10/supervisor-2021.01.7

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by MartinHjelmare** [comment] 2021-02-06 15:35
Duplicate of https://github.com/home-assistant/core/issues/46066

**Closed by MartinHjelmare** 2021-02-06 15:35 UTC
