### ISSUE TITLE
Terminal & SSH Add-on Web-UI doesn't show text on Safari 15.1 (on M1)

### ISSUE THREAD

**Issue by rfrush** [home-assistant/addons#2277] opened 2021-11-22 19:17 UTC
### Describe the issue you are experiencing

When I open the Web-UI for the Terminal & SSH add on, all of the text is missing.  There is a cursor showing, and commands can be typed, but the results cannot be seen.   Opening a separate session in Firefox shows that the commands typed in the window on Safari are being handled, so this is an issue with the font rendering on Safari.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Terminal & SSH

### What is the version of the add-on?

9.2.1

### Steps to reproduce the issue

1.  Using Safari 15.1, open Web-UI Terminal.

### Anything in the Supervisor logs that might be useful for us?

```txt
no.
```

### Additional information

![terminal_screen_shot](https://user-images.githubusercontent.com/3537299/142921787-a04b993b-2e73-4df9-b5e2-3f51760c3b3d.jpg)

**Comment by ludeeus** [comment] 2021-11-22 19:18
Duplicate of https://github.com/home-assistant/addons/issues/2186

**Closed by ludeeus** 2021-11-22 19:18 UTC
