### ISSUE TITLE
Can't access via https://{IP}

### ISSUE THREAD

**Issue by Greali** [home-assistant/addons#2563] opened 2022-06-27 18:09 UTC
### Describe the issue you are experiencing

Hi,

Recently, I updated the add-on version to the 3.1.5 and my setup stopped working.
I want to use HTTPS to access HA even on local network, so I configured the add-on to use a self signed certificate and use the IP as the domain.
When I enter HA using https://{IP} I receive the error "ERR_SSL_UNRECOGNIZED_NAME_ALERT".
I investigated and is because you've added the ssl_reject_handshake on; directive to the nginx configuration on version 3.1.3.
I want to use a previous version like 3.1.2 because I understand you prefer this option now better that create fake certificates, but I searched on Google and everyone says that the only option is to recover a backup and I don't have one :S

Do you have a recommendation to my case?
Or maybe a workaround could be implemented.
I don't know I'm the only one in the whole Internet with this setup haha but I preferred to explain my case to help others.

Thank you,
Greali

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

NGINX Home Assistant SSL proxy

### What is the version of the add-on?

3.1.5

### Steps to reproduce the issue

1. Install the add-on.
2. Configure a self signed certificate and the IP of the HA server as domain.
3. Restart the add-on.
4. Try to enter https://{IP}

**Comment by mdegat01** [comment] 2022-06-27 18:55
The `ssl_reject_handshake on;` directive was only added to the fallback config. It is only used when you connect to HA via a domain other then the one listed in the config. So if you add `domain: '{IP}'` to your config that's fine and it will use your certificate when someone connects to it via `https://{IP}`.

Also just to clarify, #2532 changed the fallback config from this:
```
    server {
        server_name _;
        listen 80 default_server;
        listen 443 ssl http2 default_server;
        ssl_certificate /data/ssl-cert-snakeoil.pem;
        ssl_certificate_key /data/ssl-cert-snakeoil.key;
        return 444;
    }
```
to this:
```
    server {
        server_name _;
        listen 80 default_server;
        listen 443 ssl http2 default_server;
        ssl_reject_handshake on;
        return 444;
    }
```
Notice that before and after this is not a reverse proxy config. It always had a static return of `444` which is an error code and means "close the connection as quickly as possible". Even in prior releases this path did not forward connections on to HA, it simply closed them. If your setup was working then it definitely wasn't going down this path.

Is your goal here to enable SSL for both LAN access and external access using two different domains? If so this addon doesn't support that. This addon enables SSL access for exactly one domain (hence why the `domain` option only accepts a single URL). The expectation is that you use SSL for external access and allow unencrypted access on your LAN. Or run a local DNS server to do a rewrite so the same domain works on LAN and externally but resolves to two different IP addresses.

If you want SSL access for both LAN and external using two different domains each with their own certificate then you should use a different reverse proxy that supports that. The [nginx proxy manager addon](https://github.com/hassio-addons/addon-nginx-proxy-manager) in the community addon repo supports this for example.

**Comment by Greali** [comment] 2022-06-27 21:50
> The `ssl_reject_handshake on;` directive was only added to the fallback config. It is only used when you connect to HA via a domain other then the one listed in the config. So if you add `domain: '{IP}'` to your config that's fine and it will use your certificate when someone connects to it via `https://{IP}`.
> 
> Also just to clarify, #2532 changed the fallback config from this:
> 
> https://github.com/home-assistant/addons/blob/d37b21354316c7266a5d7616a553bfe15da5af71/nginx_proxy/data/nginx.conf#L26-L33
> 
> 
> to this:
> https://github.com/home-assistant/addons/blob/5d21f08245dd0fac4183169fe43848c05547c401/nginx_proxy/data/nginx.conf#L26-L32
> 
> 
> Notice that before and after this is not a reverse proxy config. It always had a static return of `444` which is an error code and means "close the connection as quickly as possible". Even in prior releases this path did not forward connections on to HA, it simply closed them. If your setup was working then it definitely wasn't going down this path. A real reverse proxy config in nginx looks like this for reference, notice the `location` and `proxy_*` directives:
> https://github.com/home-assistant/addons/blob/5d21f08245dd0fac4183169fe43848c05547c401/nginx_proxy/data/nginx.conf#L42-L70
> 
> Is your goal here to enable SSL for both LAN access and external access using two different domains? If so this addon doesn't support that. This addon enables SSL access for exactly one domain (hence why the `domain` option only accepts a single URL). The expectation is that you use SSL for external access and allow unencrypted access on your LAN. Or run a local DNS server to do a rewrite so the same domain works on LAN and externally but resolves to two different IP addresses.
> 
> If you want SSL access for both LAN and external using two different domains each with their own certificate then you should use a different reverse proxy that supports that. The [nginx proxy manager addon](https://github.com/hassio-addons/addon-nginx-proxy-manager) in the community addon repo supports this for example.

Thank you for your fast reply :)

In my case this add-on perfectly fit my needs.
I only want 1 LAN domain with SSL connection.

With this configuration worked on 3.1.1 version.

`
domain: 192.168.0.XX
hsts: max-age=31536000; includeSubDomains
certfile: fullchain.pem
keyfile: privkey.pem
cloudflare: false
customize:
  active: false
  default: nginx_proxy_default*.conf
  servers: nginx_proxy/*.conf
`

After the update it started giving me the mentioned error.
Also, I checked this post where it clearly says that when you use that nginx configuration "https://<ip> is no longer accessible".

https://www.codedodle.com/disable-direct-ip-access-nginx.html

Maybe this is not the problem from 3.1.1 to 3.1.5, but for me seemed like the key change that maybe broke my setup. (indirectly)

Event I tried this other path.
I were the whole afternoon trying to install the version 3.1.2.
I cloned the git repo, added "init: false" to the config and commented the image so the docker image is built locally.
But is giving my the parse errors.

![Screenshot_20220627_232333_io homeassistant companion android](https://user-images.githubusercontent.com/9323856/176040864-6876b9c7-c243-422b-b699-1c4ddb251487.jpg)

Could you test my setup to verify that the SSL error is happening?

Thank you.

**Comment by mdegat01** [comment] 2022-06-28 15:19
Ok so I dug in a bit. First the problem isn't related to the article you sent. It's a bit misleading because the article is saying this setup disabled direct IP access. Which is true but what they aren't saying is "because we want everyone to use `www.codedoodle.com`".

Notice in the last example "Disable Direct IP Access Using IF" they finally show their actual task. They have a domain (`www.codedoodle.com`), that's what they want everyone to use. Their goal therefore is to disable any other way of reaching the server (like direct IP access *in their case*). So to do that they use the exact same config we're using: add a fallback server that goes nowhere.

This is not the same as your task. In your task the desired domain *is* the IP address, there is no alternate. So the fallback server won't apply to access via IP address. See the difference? They aren't actually disabling IP address access, their disabling all routes to the server except the desired one. When the desired one is the IP then that's not disabled.

That being said, I tested your config and it doesn't work. The reason why is actually this from the NGinx docs:
> **Name-based HTTPS servers**
> 
> A common issue arises when configuring two or more HTTPS servers listening on a single IP address:
> 
```
    server {
        listen          443 ssl;
        server_name     www.example.com;
        ssl_certificate www.example.com.crt;
        ...
    }

    server {
        listen          443 ssl;
        server_name     www.example.org;
        ssl_certificate www.example.org.crt;
        ...
    }
```
> 
> With this configuration a browser receives the default server’s certificate, i.e. www.example.com regardless of the requested server name. This is caused by SSL protocol behaviour. The SSL connection is established before the browser sends an HTTP request and nginx does not know the name of the requested server. Therefore, it may only offer the default server’s certificate.

(from [here](https://nginx.org/en/docs/http/configuring_https_servers.html) scroll to "Name-based HTTPS servers", I can't link sections)

There was a similar issue in #2558 which was fixed by changing a cloudflare setting to use SNI. Most modern browsers use SNI which then allows Nginx to get to the right certificate before negotiation begins.

However SNI doesn't work when accessing the server by IP address. Which made me wonder, what actually happened in prior releases? I reverted to a prior version of the addon and tested:
![Screen Shot 2022-06-28 at 11 11 53 AM](https://user-images.githubusercontent.com/2037026/176215408-086a28fb-f24b-4b6f-8668-1f14cf7c3524.png)

This is the snakeoil cert. You can tell by `CN=localhost`. The certificate I put in the config has `CN = odroid-dev.lan`. It's not actually using the certificate I put in the config at all. So this never worked. It just appeared to because you were expecting a certificate error either way and didn't notice that the certificate being served was actually the wrong one.

Since this never actually worked correctly I'm going to close it. It may have appeared functional but getting the snakeoil certificate is not actually working, it just wasn't as obvious it was broken. To do what you're trying to do you'll need to use a different proxy as this one is not designed for direct IP address access.

**Closed by mdegat01** 2022-06-28 15:19 UTC
Labels: add-on: nginx_proxy
