### ISSUE TITLE
Zwavejs update to 1.46 broke all communication to nodes

### ISSUE THREAD

**Issue by mkono87** [home-assistant/addons#2257] opened 2021-11-07 16:22 UTC
## Environment

- Add-on with the issue: Zwavejs
- Add-on release with the issue: 1.46
- Last working add-on release (if known): 1.45
- Operating environment (OS/Supervised): OS

## Problem-relevant configuration

```
Using an Aeotec gen5 stick. Confirmed stick is visible in HA. All node are showing unavailable. Cannot communicate with controller.
```

**Comment by MartinHjelmare** [comment] 2021-11-07 16:24
Are you running Home Assistant in a Virtual Machine?

**Comment by Cirion75** [comment] 2021-11-07 18:19
I am running in a VM on Unraid, and lost my entire Z-wave network. Restore of backup did not work for me.
Install in a new VM with a restore of the backup worked, but still on 0.1.45.

Second upgrade to 0.1.46 gave the same result.

**Comment by kvg789** [comment] 2021-11-07 18:44
Same for me running HA supervised on debian as a esxi vm. Container port passthru issue? I reverted to a old zwavejs backup, which makes it again functional. (Unfortunately this old zwavejs backup is not compatible with the 2021.11 release JS integration… so my zwave network is unavailable for moment)
Note that I reran the integration scripts/packages on debian  just now before i again upgraded the container to 1.46… still broken… so looks like a aeotech+containter v1.46 issue?

**Comment by kvg789** [comment] 2021-11-07 18:50
2021-11-07T18:37:35.900Z CNTRLR   Performing soft reset...
2021-11-07T18:37:35.907Z CNTRLR   Waiting for the controller to reconnect...
2021-11-07T18:37:37.409Z CNTRLR   Waiting for the Serial API to start...
2021-11-07T18:37:42.415Z CNTRLR   Did not receive notification that Serial API has started, checking if it respo
                                  nds...
2021-11-07T18:37:43.420Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-11-07T18:37:43.521Z CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try in 1100 ms.
2021-11-07T18:37:44.625Z CNTRLR   Serial API did not respond, trying again in 2 seconds...



And repeatedly:

1-11-07 19:37:31 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.ADD hardware /dev/bus/usb/002/084 - None
21-11-07 19:37:31 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.ADD hardware /dev/ttyACM0 - /dev/serial/by-id/usb-0658_0200-if00
21-11-07 19:37:42 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.REMOVE hardware /dev/ttyACM0 - /dev/serial/by-id/usb-0658_0200-if00
21-11-07 19:37:42 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.REMOVE hardware /dev/bus/usb/002/084 - None

**Comment by kvg789** [comment] 2021-11-07 18:59
Already covered in issue #2252

**Comment by MartinHjelmare** [comment] 2021-11-07 19:11
Closing as duplicate of #2252 until further info.

**Closed by MartinHjelmare** 2021-11-07 19:11 UTC
