### ISSUE TITLE
Deconz through ingress has an unselectable system

### ISSUE THREAD

**Issue by PaulAntonDeen** [home-assistant/addons#947] opened 2019-12-24 11:03 UTC
I have updated to Deconz 5.0 and HA 103.4 HassOS 3.7 and when I use the Deconz addin through ingress I get a page where I can see my Conbee stick but not select it (it is grayed out):
![image](https://user-images.githubusercontent.com/25848961/71410446-93a6c300-2645-11ea-821a-925560f907ce.png)

Everything else that was configured before upgrading to version 4 of Deconz still works, I just cannot use the deconz web interface to add new things or change config.

**Comment by frenck** [comment] 2019-12-24 12:45
Hi there!

Thanks for opening an issue. It might be caused by previous data stored in your browser cache (cookies to be more exact). Be sure to clean your browser cache including cookie/application data.

For testing, you could try using a browser in incognito mode.

**Comment by PaulAntonDeen** [comment] 2019-12-24 13:18
When opening HA in an incognito window I do not see anything except the P on top of the page. When clicking on that, the search for gateways starts and that seems to go on forever. (I can still control all the lights connected to the stick).

Clearing all cookies and loading through a normal chrome window yields the same behavior. (chrome on Mac, I will try another browser and OS to see if that makes a difference).

**Comment by PaulAntonDeen** [comment] 2019-12-24 13:22
Found something: I normally approach my home assistant with its external domain https://my.domain.com:8123/core_deconz and ssl (even when I'm home). When I change the domain to its local IP adres https://192.168.2.103:8123/core_deconz suddenly things work great and I control my deconz stick.

**Comment by frenck** [comment] 2019-12-24 13:41
That is interesting. I use a similar setup (where I use my external domain name internally as well), including SSL and I'm not experiencing that issue on any of my systems.

Nevertheless, thank you for sharing details, will look into this a bit more and see if I can find a way to reproduce your issue.

**Comment by PaulAntonDeen** [comment] 2019-12-24 15:08
For your diagnostics:
I'm using the let's encrypt addon for the certificate
in configuration.yaml I have:
`
http:
  base_url: https://my.domain.com:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
`
In my router port forwarding is configured for 80 and 8123
The setup runs on hassio on a RPI3+

**Comment by asbl** [comment] 2019-12-24 16:45
Thx. I'm using deconz in hassio without https. After updateing hassio and deconz addon, I had the same problem with chrome and firefox, so deconz was not usable. With your workaround I was able to use the interface again.

**Comment by D3nnisd** [comment] 2019-12-30 11:53
@frenck #941 is not fixed by any means. I am unable to use that. Further more i am now experiencing the same behaviour as @PaulAntonDeen.

What i did notice, is that it uses 8081. Is this port needed ? I believe that that port is used by Motioneye aswell.

**Comment by saruter** [comment] 2019-12-30 21:13
Hi, I have the same issue when using Deconz Addon 5.0 via Ingress behind a Apache reverse proxy with SSL. I am seeing only the Phoscon "P"-Logo. Access via local http://hassio.local:8123 in browser works fine.
My setup:
- HassOS: 3.7
- Home Assistant: 103.5
- Deconz Addon: 5.0
- using Home Assistant via apache webserver as reverse-proxy and SSL
- use it from inside and outside my home network under domain https://smarthome.xyz.tld

I tried restarting Home-Assistant/Deconz Addon several times and cleared browser cache and tried incognito mode in Firefox and Chrome.
I tried setting the "base_url" parameter in configuration.yml to "https://smarthome.xyz.tld" as mentioned before, but that didn't changed anything.

What I see in the network tab in the firefox developer tools is the following:
Normal requests go to "https://smarthome.xyz.tld" whereas shortly after the Deconz Phoscon App is selected and only the Phoscon logo is visible, I see requests to "https://192.168.179.175/api/hassio_ingress/Ud2cwvHajsRCsIXVWEQ0ZueliqRvRxupzvsrwsfGPNA/api/config?_=1577739126418" which is strange because this address is the laptop I'm accessing Home Assistant and not the server which is serving Home Assistant...
![deconz-error](https://user-images.githubusercontent.com/57154423/71600685-616af900-2b50-11ea-8b7f-9335e5ade098.png)
Probably this helps solving the problem or getting nearer to a solution...

**Comment by mira2002** [comment] 2020-01-04 17:08
Das habe ich auch und es ist sicher ein CORS Problem, dass für die Ajax Requests über Javascript die falsche Domain / IP verwendet wird. Hier die Meldung aus der Browser Console:

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://192.168.178.25/api/hassio_ingress/m6-hgvHOoz-Wz8P2LeQK34cnP1T1fDzKVca3jHgajTk/api/config?_=1578157483133. (Grund: CORS-Anschlag schlug fehl).

**Comment by schneekluth** [comment] 2020-01-30 22:30
> Found something: I normally approach my home assistant with its external domain https://my.domain.com:8123/core_deconz and ssl (even when I'm home). When I change the domain to its local IP adres https://192.168.2.103:8123/core_deconz suddenly things work great and I control my deconz stick.

Same here on 0.104.3 running behind [nginx-proxy-manager](https://github.com/jc21/nginx-proxy-manager). I have set `base_url`,  `use_x_forwarded_for`and `trusted_proxies` in `configuration.yaml` and access my hass.io via same url externally and in my home network. Deconz Web UI only works with internal IP. External url just shows the "P" logo without any gateway discovered.

**Comment by PaulAntonDeen** [comment] 2020-02-05 09:53
The problem still persists on Deconz 5.1 with HA 0.104.3

**Comment by SukramJ** [comment] 2020-03-06 12:33
The problem still persists on Deconz 5.3.1 with HA 0.106.5.

It works without TLS, but still an issue with TLS an NGINX Reverse Proxy.

**Comment by PaulAntonDeen** [comment] 2020-03-06 12:39
Confirmed here as well

**Comment by PaulAntonDeen** [comment] 2020-04-05 16:05
Still broken

**Comment by Sirezul** [comment] 2020-04-16 14:21
Same for me, still broken with SSL.
Local IP works.

**Comment by saruter** [comment] 2020-05-16 17:46
Still broken...

**Comment by PaulAntonDeen** [comment] 2020-06-10 06:08
Still broken on HA 110.6 with deconz 5.3.5

**Comment by Mimiix** [comment] 2020-06-10 06:14
I'm wondering, i've had this issue only when i used my external_ip in HA.

However, what browser are you using @PaulAntonDeen ?

**Comment by PaulAntonDeen** [comment] 2020-06-10 06:22
I use Chrome on Mac and Windows and the problem occurs on both. My HA (formerly called Hassio) is running on an rPi which has port 8123 and 80 port forwarded to it from my router. For me the issue occur when I use my private domain to access HA and it does not matter if I am internally connected to the WiFi or externally connected to another network. When I'm connected to local wifi I can change just the domain part to the local IP of the Pi and everything works fine.

**Comment by PaulAntonDeen** [comment] 2020-06-10 06:25
And just confirmed the problem using MS Edge 42.17134.1098.0 (the pre-chrome version) as well.

**Comment by Mimiix** [comment] 2020-06-10 06:36
That's not the issue.

In HA, 40850 is the port that's used (afaik). What happens if you portforward that 40850 in the router aswell?

**Comment by PaulAntonDeen** [comment] 2020-06-10 06:59
No difference when port forwarding that one as well. You see in the Deconz logs that it is contacting itself on port 8123.

GET /api/config HTTP/1.1" 200 263 "https://**.**.**:8123/api/hassio_ingress/uL8ItLFEWDEy5QFNhRMZH6YV6T-yWLILWdBlsKkeo/pwa/login.html?1591772140245" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36"

**Comment by Mimiix** [comment] 2020-06-10 07:00
It's not deCONZ doing that, it's the implementation of the ingress thing. Unfortunately, that's not something deCONZ should fix.  Should wait on a addon dev.

**Comment by PaulAntonDeen** [comment] 2020-06-10 08:54
Thanks for your help thinking through the problem. My guess the problem is in Ingress configuration.
Using my domain URL or my internal IP address, nothing happens at port 40850. It cannot reach a website there. I think when Deconz moved to exposing the web-end through ingress, it stopped being accessible any other way. That is also when these problems started. So if I access ingress through my internal IP but with the rest of the URL exactly the same, it all works fine (still on port 8123).

**Comment by Mimiix** [comment] 2020-06-10 08:58
Wait, you forwarded to port 80 right?

What happens if you put that back to 40850?

**Comment by PaulAntonDeen** [comment] 2020-06-10 09:02
Initially no, i forwarded to 40850, but now I tried forwarding to 80 and 8123. No difference.

**Comment by mira2002** [comment] 2020-06-10 09:04
Hi,

I get the follwing error in the chrome console when I start the addon page over ingress:

![image](https://user-images.githubusercontent.com/29159500/84248608-f7487e00-ab09-11ea-8e2d-46c6b87653f9.png)

**Comment by Mimiix** [comment] 2020-06-10 09:12
@PaulAntonDeen For me it always worked when i put http://internalip:40850/pwa/

Make sure not to use HTTPS on this. Phoscon doesn't seem to speak HTTPS.

**Comment by PaulAntonDeen** [comment] 2020-07-11 06:42
Still a problem

**Comment by Sirezul** [comment] 2020-08-16 10:20
Still a thing.

**Comment by SukramJ** [comment] 2020-09-20 18:22
Still an issue with Phoscon Web App.
The deCONZ application works.

**Comment by schneekluth** [comment] 2020-09-21 12:30
> Still an issue with Phoscon Web App.
> The deCONZ application works.

Same here.

**Comment by oashour** [comment] 2020-10-09 03:40
Still broken.

**Comment by wauswaus** [comment] 2020-10-09 15:39
looks like nobody wants to fix this

**Comment by tazztone** [comment] 2020-10-25 11:18
gateway is never to be found when clicking on the "phoscon app" button inside deCONZ (win10 latest deconz version).
also the "webapp" will not allow to reset the pw or say "error! on sending login data"

still dealing with the usb reconnect loop issue and **trying to update firmware** which always fails in deconz within hass.io.

overall this conbeeII is a disaster

**Comment by pawlizio** [comment] 2021-01-05 18:31
I have same problems, but I use a reverse proxy, so all the domain certification is done on a seperate server. When accessing via public domain, I just see the P of phoscon app, no gateway. If I open via local domain everything works great.

**Comment by ottelo9** [comment] 2021-01-13 08:54
> I have same problems, but I use a reverse proxy, so all the domain certification is done on a seperate server. When accessing via public domain, I just see the P of phoscon app, no gateway. If I open via local domain everything works great.

I use reverse proxy, too. Have the same problem!

**Comment by robertmx** [comment] 2021-04-12 13:49
Still an issue :-/. Even without a reverse proxy (but an external DNS name) the phoscon app doesn't work. It seems the ingress routing is broken. I see a lot of XHR requests, that have the resource path duplicated and some others failing for no obvious reason.

**Comment by Sirezul** [comment] 2021-04-12 16:20
> Still an issue :-/. Even without a reverse proxy (but an external DNS name) the phoscon app doesn't work. It seems the ingress routing is broken. I see a lot of XHR requests, that have the resource path duplicated and some others failing for no obvious reason.

@frenck could you help us with this one? It's been so long and this issue is still open. Any help is very much appreciated. If more information is needed I can provide it.🙏

**Comment by stepman0** [comment] 2021-05-28 12:40
Same problem here... Any hints?

**Comment by LeoLTM** [comment] 2021-07-30 15:50
Still an existing problem... ran into it while configuring my ConBee II today...

**Comment by felixfischer** [comment] 2021-08-09 15:58
Absolutely not stale!

**Comment by maikalms** [comment] 2021-09-09 19:58
Still Broken..

**Comment by Syrox94** [comment] 2021-09-14 21:59
Still not working with reverse proxy :/

**Comment by zybster** [comment] 2021-10-12 11:21
I'm experiencing the same issue - Only the P show's up in Phoscon app when calling it via external domain.
Only works when accessing Homeassistant via LAN IP:8123
A fix would be greatly appreciated.

**Comment by TekkertheChaot** [comment] 2021-11-10 18:25
Same issue here! Local IP access works, but as soon as I try to connect from external SSL domain, it doesn't

**Comment by cairon-ha** [comment] 2021-12-09 14:03
Same issue here on core-2021.11.5 on supervisor-2021.10.8 and Home Assistant OS 6.6

It took me quite a while to find that issue and configure the Gateway.

Some said that switching from https to http can be a solution. Do you know how I can do that?

Thanks!

**Comment by Iscanniya** [comment] 2021-12-20 18:35
Now I'm with you. Today, for no reason, I cannot access the gateway. It's only telling me, that it scans for gateways, but nothing happens. Using core-2021.12.3 and supervisor-2021.12.2 and Home Assistant OS 7.0

I thought it'd be the ConBee II Stick, so I resetted it with firmware flashing tool. Now, I can see in my logs corresponding to the gateway entry:
21-12-20 18:47:54 WARNING (MainThread) [supervisor.api.middleware.security] No API token provided for /api/8FE2467DF1

How to connect to that ConBee Stick again, if i cannot enter the Phoscon Page?

**Comment by wauswaus** [comment] 2021-12-20 18:41
That is unrelated to this issue, see https://community.home-assistant.io/t/deconz-official-thread/100504/2800
Has something to do with the Deconz update to 6.11.0

**Comment by DanielTheCoder** [comment] 2021-12-20 18:45
I've upgraded already to 6.11.1 which should solve access problem.
https://github.com/home-assistant/core/issues/62388#issuecomment-998147134

**Comment by mueslo** [comment] 2022-01-19 20:10
I am using the deCONZ 6.11.1 addon and the issue persists.

**Comment by TekkertheChaot** [comment] 2022-02-19 09:32
Issue is not resolved yet.

**Comment by felixfischer** [comment] 2022-03-21 10:29
Issue is not resolved yet.

**Comment by felixfischer** [comment] 2022-04-27 12:38
And that's how you reduce the number of open issues simply by doing nothing. Genius!

**Comment by tannyl** [comment] 2022-04-28 12:18
@felixfischer hopefully https://github.com/home-assistant/addons/pull/2325/ will get merged very soon and I hope that will finally fix this problem.

**Comment by mdegat01** [comment] 2022-04-28 12:32
Damn, forgot to remove stale in time. Just for you @felixfischer I'll reopen it so it can close for real 😄

**Closed** 2022-04-28 12:33 UTC
Labels: add-on: deconz

**Comment by felixfischer** [comment] 2022-04-28 15:16
Awesome! I can confirm that the issue has been resolved! 🚀 👍
