### ISSUE TITLE
  VLC: raspberry pi 4b cannot play sound through local 3.5 mm audio socket

### ISSUE THREAD

**Issue by holefrog** [home-assistant/addons#2819] opened 2022-12-30 08:35 UTC
### Describe the issue you are experiencing

I have HAOS install on raspberry pi 4b .
I tried to call service to play a wav file through raspberry pi's local 3.5mm audio socket, but there is no sound output. And there is no error neither.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

VLC

### What is the version of the add-on?

 0.1.3 

### Steps to reproduce the issue

I tried to call service to play a wav file through raspberry pi's local 3.5mm audio socket, but there is no sound output. And there is no error neither.

```

service: media_player.play_media
data:
  media_content_id: media-source://media_source/local/alarm.wav
  media_content_type: music
target:
  device_id: ae6aa59cd8d47e303305535df8c4918c
```

### System Health information

```
## System Information

version | core-2022.12.8
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.76-v8
arch | aarch64
timezone | America/Vancouver
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.12.1
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 28.5 GB
disk_used | 7.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.0), VLC (0.1.3), Duck DNS (1.15.0), Mosquitto broker (6.1.3), Xiaomi Mi Scale (0.3.6), File editor (5.4.2), Terminal & SSH (9.6.1), Dnsmasq (1.5.1), ESPHome (2022.12.3), AirCast (3.5.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 25, 2022 at 1:03 AM
-- | --
current_recorder_run | December 30, 2022 at 12:12 AM
estimated_db_size | 131.71 MiB
database_engine | sqlite
database_version | 3.38.5

</details>
```

### Anything in the add-on logs that might be useful for us?

```txt
172.30.32.2 - - [30/Dec/2022:08:19:32 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:19:34 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:19:36 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:19:38 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:19:40 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:19:42 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:19:44 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:19:46 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:19:48 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:19:50 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:19:52 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:19:54 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:19:56 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:19:58 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:00 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:02 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:04 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:05 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:07 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:09 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:11 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:13 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:15 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:17 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:19 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:21 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:23 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:25 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:27 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:29 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:31 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:33 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:35 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:37 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:39 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:41 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:43 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:45 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:47 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:49 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:51 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:53 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:55 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:57 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:20:59 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:01 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:03 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:05 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:07 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:09 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:11 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:13 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:15 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:17 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:19 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:21 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:23 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:25 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:27 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:29 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:31 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:33 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:35 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:37 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:39 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:41 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:43 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:45 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:46 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:47 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
[0000007fa44609d0] main playlist: playlist is empty
172.30.32.2 - - [30/Dec/2022:08:21:47 +0000] "GET /requests/status.xml?command=pl_play&id=2 HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:48 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
[0000007fa44609d0] main playlist: playlist is empty
172.30.32.2 - - [30/Dec/2022:08:21:48 +0000] "GET /requests/status.xml?command=pl_play&id=1 HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
[0000007fa44609d0] main playlist: playlist is empty
172.30.32.2 - - [30/Dec/2022:08:21:49 +0000] "GET /requests/status.xml?command=pl_play&id=2 HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
[0000007fa44609d0] main playlist: playlist is empty
172.30.32.2 - - [30/Dec/2022:08:21:49 +0000] "GET /requests/status.xml?command=pl_play&id=2 HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:49 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
[0000007fa44609d0] main playlist: playlist is empty
172.30.32.2 - - [30/Dec/2022:08:21:50 +0000] "GET /requests/status.xml?command=pl_play&id=1 HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:50 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
[0000007fa44609d0] main playlist: playlist is empty
172.30.32.2 - - [30/Dec/2022:08:21:51 +0000] "GET /requests/status.xml?command=pl_play&id=2 HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:51 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:52 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:53 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:55 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:56 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:57 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:58 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:21:59 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:22:00 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:22:01 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:22:02 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:22:03 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:22:04 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:22:05 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.30.32.2 - - [30/Dec/2022:08:22:06 +0000] "GET /requests/status.xml HTTP/1.1" 200 759 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
```
```


### Additional information

# cat /mnt/data/supervisor/audio/asound
```
pcm.!default {
    type plug
    slave.pcm "btreceiver"
}

pcm.btreceiver {
    type plug
    slave {
        pcm {
            type bluealsa
            device 8C:53:C3:FD:8F:1A
            profile "a2dp"
        }
    }
    hint {
        show on
        description "X08A"
    }
}

ctl.!default {
    type bluealsa
}

```

**Comment by mib1185** [comment] 2022-12-30 11:40
see https://github.com/home-assistant/core/issues/84837#issuecomment-1367873128

**Comment by MartinHjelmare** [comment] 2022-12-30 11:54
Duplicate of https://github.com/home-assistant/core/issues/84754

**Closed by MartinHjelmare** 2022-12-30 11:54 UTC
