### ISSUE TITLE
Matter Server Restarting

### ISSUE THREAD

**Issue by LordNex** [home-assistant/addons#2800] opened 2022-12-13 13:25 UTC
### Describe the issue you are experiencing

Server logs show constant restarting

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Check Home Assistant configuration

### What is the version of the add-on?

Matter Server

### Steps to reproduce the issue

1.
2.
3.
...

## System Information

version | core-2022.12.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.80
arch | x86_64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 3800
Installed Version | 1.28.4
Stage | running
Available Repositories | 1228
Downloaded Repositories | 93

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | March 2, 2023 at 6:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | us-east-1-2.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.11.2
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 491.4 GB
disk_used | 70.8 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | AdGuard Home (4.7.5), AirCast (3.5.0), AirSonos (3.5.0), Double Take (1.13.1), Duck DNS (1.15.0), ESPHome (2022.11.5), File editor (5.4.2), Frigate NVR Proxy (1.3), MariaDB (2.5.1), Matrix (0.10.0), Z-Wave JS (0.1.74), Studio Code Server (5.4.1), SSH & Web Terminal (13.0.0), Traccar (0.17.0), Tor (4.0.2), MQTT IO (0.1.3), chrony (2.4.0), Z-Wave JS UI (1.4.0), TasmoAdmin (0.21.0), Spotify Connect (0.12.2), Node-RED (14.0.0), Samba share (10.0.0), Genie (3.0.0), Mosquitto broker (6.1.3), Samba Backup (5.2.0), NGINX Home Assistant SSL proxy (3.2.0), Matter Server (1.1.0), Exadel CompreFace (1.1.0), go2rtc (0.1-rc.5), Hey Ada! (1.2.0), AppDaemon (0.10.1), Bookstack (1.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 54
views | 10
mode | storage

</details>

<details><summary>NextDNS</summary>

can_reach_server | ok
-- | --

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 16, 2022 at 3:47 PM
-- | --
current_recorder_run | December 13, 2022 at 6:37 AM
estimated_db_size | 19052.23 MiB
database_engine | mysql
database_version | 10.6.8

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
[07:16:46] INFO: Starting Matter Server...
usage: matter-server [-h] [--vendorid VENDORID] [--fabricid FABRICID]
                     [--storage-path STORAGE_PATH] [--port PORT]
                     [--log-level LOG_LEVEL] [--log-file LOG_FILE]
matter-server: error: argument --port: invalid int value: ''
```

**Comment by MartinHjelmare** [comment] 2022-12-13 13:34
Duplicate of https://github.com/home-assistant/addons/issues/2801

That one has a bit more logs. Closing here.

**Closed by MartinHjelmare** 2022-12-13 13:34 UTC
