### ISSUE TITLE
SSH connections fail to connect Home Assistant

### ISSUE THREAD

**Issue by jakadia** [home-assistant/addons#2586] opened 2022-07-08 03:11 UTC
### Describe the issue you are experiencing

I am using a un/pass to upload files into my share folder. Since I upgraded to 9.6 some of my connections are failing to negotiate. 

`Server listening on :: port 22.`
`Accepted password for root from 192.168.100.80 port 39018 ssh2`
`Unable to negotiate with 192.168.1.85 port 50192: no matching host key type found. Their offer: ssh-rsa,ssh-dss [preauth]`

The accepted one was when I logged in via SCP - works great
The failed connection is a server I have running on my farm that uploads a file every 5 mins to my share folder with barn data.  I am unable to upgrade OPENSSH on this server so what are my options?  Is there anyways I can roll back this addon?

Here is my current config - 
`authorized_keys: []`
`password: **************`
`apks: []`
`sftp: true`
`compatibility_mode: true`
`server:`
     ` tcp_forwarding: false`

Any help would be greatly appreciated!

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Terminal & SSH

### What is the version of the add-on?

9.6.0

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the add-on logs that might be useful for us?

```txt
[21:58:17] INFO: Starting Web Terminal...
[2022/07/07 21:58:17:0923] N: ttyd 1.6.3-3e37e33 (libwebsockets 4.2.1-v4.2.1)
[2022/07/07 21:58:17:0923] N: tty configuration:
[2022/07/07 21:58:17:0923] N:   start command: tmux -u new -A -s homeassistant bash -l
[2022/07/07 21:58:17:0924] N:   close signal: SIGHUP (1)
[2022/07/07 21:58:17:0924] N:   terminal type: xterm-256color
[2022/07/07 21:58:17:0924] N: LWS: 4.2.1-v4.2.1, loglevel 7
[2022/07/07 21:58:17:0924] N: NET CLI SRV H1 H2 WS ConMon IPV6-off
[2022/07/07 21:58:17:0931] N:    /usr/lib/libwebsockets-evlib_uv.so
[2022/07/07 21:58:17:1039] N:  Using foreign event loop...
[2022/07/07 21:58:17:1039] N:  ++ [wsi|0|pipe] (1)
[2022/07/07 21:58:17:1040] N:  ++ [vh|0|netlink] (1)
[2022/07/07 21:58:17:1040] N:  ++ [vh|1|default||8099] (2)
[2022/07/07 21:58:17:1041] N: lws_socket_bind: nowsi: source ads 0.0.0.0
[2022/07/07 21:58:17:1041] N:  ++ [wsi|1|listen|default||8099] (2)
[2022/07/07 21:58:17:1041] N:  Listening on port: 8099
[21:58:17] INFO: Starting the SSH daemon...
Server listening on 0.0.0.0 port 22.
Server listening on :: port 22.
Accepted password for root from 192.168.100.80 port 39018 ssh2
Unable to negotiate with 192.168.1.85 port 50192: no matching host key type found. Their offer: ssh-rsa,ssh-dss [preauth]
Unable to negotiate with 192.168.1.85 port 50193: no matching host key type found. Their offer: ssh-rsa,ssh-dss [preauth]
Unable to negotiate with 192.168.1.85 port 50199: no matching host key type found. Their offer: ssh-rsa,ssh-dss [preauth]
Unable to negotiate with 192.168.1.85 port 50200: no matching host key type found. Their offer: ssh-rsa,ssh-dss [preauth]
```

**Comment by frenck** [comment] 2022-07-08 07:57
closing as a duplicate of #2584

**Closed by frenck** 2022-07-08 07:57 UTC
