### ISSUE TITLE
Information about Eclipse Mosquitto

### ISSUE THREAD

**Issue by sim-san** [home-assistant/addons#1759] opened 2021-01-11 12:14 UTC
## The problem

This not a bug. I just want to mention that there is a new major version of the Eclipse Mosquitto released. 

- [Version 2.0.0 released.](https://mosquitto.org/blog/2020/12/version-2-0-0-released/)
- [Migrating from 1.x to 2.0](https://mosquitto.org/documentation/migrating-to-2-0/)

## Environment

- Add-on with the issue: /
- Add-on release with the issue: /
- Last working add-on release (if known): /
- Operating environment (OS/Supervised): /

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by frenck** [comment] 2021-01-11 12:17
Duplicate of #1734 

See: https://github.com/home-assistant/addons/issues/1734#issuecomment-751754951

**Closed by frenck** 2021-01-11 12:17 UTC
