### ISSUE TITLE
Unknown clients connect to MQTT

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/addons#2028] opened 2021-05-21 18:33 UTC
## The problem

in the MQTT log several unknown (to me), but identified clients connect, and get disconnected. Is this a bug/danger?

## Environment

- Add-on with the issue: Mosquitto broker
- Add-on release with the issue:  6.0.1
- Last working add-on release (if known): 5.1
- Operating environment (OS/Supervised): OS

## Problem-relevant configuration

```yaml
logins:
  - username: redacted
    password: redacted
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
```

## Traceback/Error logs

```txt
1621613733: New connection from 162.142.125.40 on port 8883.
1621613733: New client connected from 162.142.125.40 as CENSYS (p2, c0, k10).
1621613748: Socket error on client CENSYS, disconnecting.
1621613901: Saving in-memory database to /data/mosquitto.db.
1621614943: New connection from 216.218.206.67 on port 8883.
1621614944: New client connected from 216.218.206.67 as MqttClient (p2, c1, k60).
1621614944: Socket error on client MqttClient, disconnecting.
```

## Additional information

Can't relate these to any configured action in the clients that are setup to subscribe to the broker. Neither the ip addresses nor the names CENSYS and MqttClient are known clients in my configuration. Whats even more significant is they apparently dont use a Username to login?

**Comment by frenck** [comment] 2021-05-21 19:28
client name is not the same as a username, those are different things
I don't see a login in the log, only a socket error. Indicating they are connecting to port 8883, but expect something different?

Usually, this is caused by the client not talking the right protocol (it expects MQTT over TLS on this port).

**Comment by Mariusthvdb** [comment] 2021-05-21 20:03
Couldn't this be caused by the fact anonymous: false is no longer allowed? I've been running Mqtt for 4 years now and never saw this.

Given the fact these logins are anonymous ( no p entered) that should be prevented in the first place.

I understand name and username are not the same,only mentioned them because the names are provided, however unknown to me. Do you recognize these at all? Maybe internal?

**Comment by kristianrd** [comment] 2021-05-23 12:00
I have the same problem after anonymous was removed. I have some clients that I'm unable to set a username and password for. Vital to me, for sure. Removing anonymous access is sadly breaking this addon for me.

Version 5.1.1. from March 15th works well with ACL list, so I really didn't see this capping of the addon come.

Setting anonymous false in 5.1.1. gives the exact same error messages as Mariusthvdb gets.

We need a workaround (preferably not) or anonymous access with ACL list back in, please.

**Comment by frenck** [comment] 2021-05-23 12:06
> Couldn't this be caused by the fact anonymous: false is no longer allowed?

No, this is a protocol error. It should not be caused by anonymous access.

> We need a workaround (preferably not) or anonymous access with ACL list back in, please.

You can create your own configuration using customize, but from Home Assistant's end, we will not be providing anonymous access for the future.

I'm closing the issue on our end, as this is not an issue.

**Closed by frenck** 2021-05-23 12:06 UTC
