### ISSUE TITLE
gandi dns not working

### ISSUE THREAD

**Issue by oweinsto68** [home-assistant/addons#3383] opened 2024-01-04 09:14 UTC
### Describe the issue you are experiencing

Hi, 
the letsencrypt addon is not working for gandi. Ive checked in the code and it only takes the sharing id parameter and doesn't read the gandi_api_key configuration parameter. By the way gandi_api_key is deprecated and should be replaced with dns_gandi_token

`# Gandi
elif [ "${DNS_PROVIDER}" == "dns-gandi" ]; then
    if bashio::config.exists 'dns.gandi_sharing_id'; then
        bashio::log.info "Use Gandi sharing ID"
        echo "dns_gandi_sharing_id = $(bashio::config 'dns.gandi_sharing_id')" >> "/data/dnsapikey"
    fi
    PROVIDER_ARGUMENTS+=("--authenticator" "${DNS_PROVIDER}" "--${DNS_PROVIDER}-credentials" "/data/dnsapikey" "--${DNS_PROVIDER}-propagation-seconds" "${PROPAGATION_SECONDS}" )
`

the following code should fix it:
`elif [ "${DNS_PROVIDER}" == "dns-gandi" ]; then
    if bashio::config.exists 'dns.gandi_sharing_id'; then
        bashio::log.info "Use Gandi sharing ID"
        echo "dns_gandi_sharing_id = $(bashio::config 'dns.gandi_sharing_id')" >> "/data/dnsapikey"
    fi
    if bashio::config.exists 'dns.dns_gandi_token'; then
        bashio::log.info "Use Gandi dns_gandi_token"
        echo "dns_gandi_token = $(bashio::config 'dns.dns_gandi_token')" >> "/data/dnsapikey"
    fi
    if bashio::config.exists 'dns.gandi_api_key'; then
        bashio::log.info "Use Gandi gandi_api_key"
        echo "gandi_api_key = $(bashio::config 'dns.gandi_api_key')" >> "/data/dnsapikey"
    fi
    PROVIDER_ARGUMENTS+=("--authenticator" "${DNS_PROVIDER}" "--${DNS_PROVIDER}-credentials" "/data/dnsapikey" "--${DNS_PROVIDER}-propagation-seconds" "${PROPAGATION_SECONDS}" )
`

Can you please implement the fix?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

5.0.9

### Steps to reproduce the issue

1. configure lets encrypt with gandi dns

### System Health information

NA

### Anything in the add-on logs that might be useful for us?

```txt
[09:56:04] INFO: Selected DNS Provider: dns-gandi
[09:56:04] INFO: Use propagation seconds: 60
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Requesting a certificate for xxxx
Unable to find or delete the DNS TXT record: Unable to get base domain for "xxxx"
An error occurred adding the DNS TXT record: Unable to get base domain for "xxxx"
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by disconn3ct** [comment] 2024-02-08 13:56
@frenck is github-actions fixing these bugs? how did you configure that? can you share the setup?

It looks like it is just closing actual bugs, but that can't be right. That would lead to tons of duplicate issues and a huge increase in maintainer workload, while simultaneously pushing new contributors out and making them feel unwanted.

**Comment by disconn3ct** [comment] 2024-03-10 12:26
/unstale
Gandi dns is still broken. Weird that software doesn't just magically heal itself over time. Maybe this can be the "year of fixing trivial bugs".

**Comment by agners** [comment] 2024-03-11 09:36
@disconn3ct your PR #3465 is currently stuck because you'll have to resolve the CLA requirements. I then can help get this over the finish line.

**Comment by disconn3ct** [comment] 2024-03-12 09:56
> @disconn3ct your PR #3465 is currently stuck because you'll have to resolve the CLA requirements. I then can help get this over the finish line.

As I said in the pr, it isn't my code to sign off on. It's copied directly from the bug report.

**Comment by agners** [comment] 2024-03-12 10:05
Well, I can't really merge without having this resolved, I am sorry :cry: 

The change is rather trivial, so we probably could see this as fair use or something but IANAL.

The CLA actually has an option to submit contribution from third parties, see c) in the [CLA agreement](https://www.home-assistant.io/developers/cla/). So I think you can sign the CLA if @oweinsto68 agrees to the CLA in here.

@oweinsto68 can you certify to (a) of the CLA? :thinking:

**Comment by disconn3ct** [comment] 2024-03-12 19:25
> Well, I can't really merge without having this resolved, I am sorry 😢

Not trying to be a pain but you have as much of a relationship with that code as I do. Why don't you just sign it?

It is literally copied from the original bug report way at the top there. And I labeled it as such. You could probably also copy it, and then you would be exactly where I am.

**Comment by disconn3ct** [comment] 2024-04-12 13:08
Weirdly it didn't magically heal itself. Maybe the robot is misconfigured? This is a real bug that has been confirmed and even has a fix!

**Closed** 2024-04-25 13:02 UTC
Labels: add-on: letsencrypt
