### ISSUE TITLE
MQTT Broker 6.0.1 issue after upgrade

### ISSUE THREAD

**Issue by Rrapa** [home-assistant/addons#2019] opened 2021-05-19 17:51 UTC
Hello guys 

Receiving a lot of errors after update to 6.0.1 as per below. Had to restore to 5.1.1

`21-05-19 17:24:19 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1219654' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=TypeError('an integer is required (got type str)')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 416, in _watchdog_addon_application
    if addon.in_progress or await addon.watchdog_application():
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 479, in watchdog_application
    return await self.sys_run_in_executor(check_port, self.ip_address, port)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 43, in check_port
    result = sock.connect_ex((str(address), port))
TypeError: an integer is required (got type str)`

**Comment by frenck** [comment] 2021-05-19 18:10
Duplicate of https://github.com/home-assistant/supervisor/issues/2902 and #2016
Fixed in https://github.com/home-assistant/supervisor/pull/2903

**Closed by frenck** 2021-05-19 18:10 UTC
