### ISSUE TITLE
Server refused our key Home Assistant Add-on: Terminal & SSH

### ISSUE THREAD

**Issue by antoweb** [home-assistant/addons#2587] opened 2022-07-08 10:15 UTC
### Describe the issue you are experiencing

No more accept authorized key after last update

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Terminal & SSH

### What is the version of the add-on?

9.6.0

### Steps to reproduce the issue

1. Try ssh connection after configured authorized key and restart addon
2. Receive error : Server refused our key
3.
...

**Comment by frenck** [comment] 2022-07-08 10:52
Anything in the logs?

**Comment by antoweb** [comment] 2022-07-08 11:10
Sorry where i have to search? Wich logs?

**Comment by antoweb** [comment] 2022-07-08 12:19
Following the log.
Same key before update was working good, now not:
[14:18:08] INFO: Starting the SSH daemon...
Server listening on 0.0.0.0 port 22.
Server listening on :: port 22.
userauth_pubkey: signature algorithm ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
Received disconnect from 192.168.1.68 port 52569:14: No supported authentication methods available [preauth]
Disconnected from authenticating user root 192.168.1.68 port 52569 [preauth]
userauth_pubkey: signature algorithm ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
Received disconnect from 192.168.1.68 port 52574:14: No supported authentication methods available [preauth]
Disconnected from authenticating user root 192.168.1.68 port 52574 [preauth]

**Comment by antoweb** [comment] 2022-07-08 12:20
Conf page
![image](https://user-images.githubusercontent.com/32364871/177990921-f9881ee2-4da1-42a2-a98c-0048c44a7c7a.png)

public key used: 
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCS/jmN8snmwhJXf7h1qfq2b+BOIjzaKQS9m2dIUlsqrBkDdj/BZKjF0CoCEb/rJgIU9q7OqV52t/Y25wdDLcG3mx9I+wfZ8uvU8cqjVuwShtuSLMQHZk5vW4JJ7gD/saRrbRzdBqOQfKki6GhEEYYr20jfSnrruW1uRKL20pptyzmIWWP1ajIQq215in6/a/Bjuk6gbGfrJn2liIzYqOz/SxpO/NWrlFFOsnhkVyh3JeSrE1lmydyp3Jgo/CjFhoo2MVH1k7uqP7Cmz8o9QPgJ1L7WjFp9es/plwa2xlZEE8YR3qXmdFpN0eM3zLt+jH75z9B5511xKEF35lb7wYtN

**Comment by frenck** [comment] 2022-07-08 12:21
> userauth_pubkey: signature algorithm ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]

This is a duplicate of #2584

**Closed by frenck** 2022-07-08 12:21 UTC

**Comment by antoweb** [comment] 2022-07-08 12:31
Ok, and how to enable

**Comment by frenck** [comment] 2022-07-08 12:49
> Ho to enable old sha1 algorithm?

You can't with the add-on. As per #2584, the suggestion is to generate new keys.
<https://github.com/home-assistant/addons/issues/2584#issuecomment-1178226289>
