### ISSUE TITLE
VNC not working

### ISSUE THREAD

**Issue by alanmilinovic** [home-assistant/addons#2670] opened 2022-09-18 08:50 UTC
### Describe the issue you are experiencing

I am getting error message when trying to open deConz app via VNC.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.15.0

### Steps to reproduce the issue

1. I am using port 5901 for VNC
2. Restart of the addon
3. When I try to open VNC connection I am getting
"Something went wrong, connection is closed"

### Anything in the Supervisor logs that might be useful for us?

```txt
2022-09-18 10:39:00.246 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/core_deconz/stats - Container addon_core_deconz is not running
2022-09-18 10:39:39.954 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/core_deconz/stats - Can't read stats from addon_core_deconz: Expecting value: line 1 column 1 (char 0)
```

### Anything in the add-on logs that might be useful for us?

```txt
06:37:20:086 SensorNode 9 set node 0x00158d000808f92e
parse error: Invalid numeric literal at line 1, column 34
06:37:20:175 DEV found DDF for 0x00158D000808F92E, path: /usr/share/deCONZ/devices/xiaomi/aq1_vibration_sensor.json
06:37:20:175 DEV no DDF for 0x00158D0007EE0EE1, modelId: lumi.sensor_wleak.aq1
06:37:20:176 DEV create on-the-fly DDF for 0x00158D0007EE0EE1
06:37:20:195 dlg action: Read binding table
06:37:20:217 DEV no DDF for 0xB4E3F9FFFEBE9477, modelId: TRADFRI control outlet
06:37:20:217 DEV create on-the-fly DDF for 0xB4E3F9FFFEBE9477
06:37:20:223 DEV found DDF for 0x00158D00086523C9, path: /usr/share/deCONZ/devices/xiaomi/xiaomi_wsdcgq11lm_temp_hum_press_sensor.json
06:37:20:224 DEV found DDF for 0xB4E3F9FFFEBE922F, path: 
06:37:20:227 DEV found DDF for 0x00158D0008651732, path: /usr/share/deCONZ/devices/xiaomi/xiaomi_wsdcgq11lm_temp_hum_press_sensor.json
06:37:21:460 Announced to internet https://phoscon.de/discover
06:37:22:162 Skip idle timer callback, too early: elapsed 937 msec
06:37:22:697 Device firmware version 0x26720700 ConBee II
06:37:22:705 unlocked max nodes: 512
06:37:22:796 Device protocol version: 0x010E
06:37:22:870 Current channel 11
06:37:22:882 CTRL got nwk update id 1
06:37:22:892 CTRL ANT_CTRL 0x03
06:37:22:893 CTRL ZDP_RESPONSE handler 0x0000
06:37:22:893 CTRL reconfigure ZDP_RESPONSE handler 0x0001
06:37:22:935 Device protocol version: 0x010E
06:37:23:020 CTRL ANT_CTRL 0x03
06:37:23:021 CTRL ZDP_RESPONSE handler 0x0000
06:37:23:021 CTRL reconfigure ZDP_RESPONSE handler 0x0001
06:37:24:162 DEV Tick.Init: booted after 8000 seconds
06:37:31:166 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26720700.bin.GCF
06:37:31:166 GW firmware version is up to date: 0x26720700
06:37:46:225 Bind response success for 0xb4e3f9fffebe922f ep: 0x01 cluster: 0x0000
06:37:46:301 ZCL configure reporting rsp seq: 10 0xB4E3F9FFFEBE922F for ep: 0x01 cluster: 0x0000 attr: 0x4000 status: 0x00
06:37:46:361 Bind response success for 0xb4e3f9fffebe922f ep: 0x01 cluster: 0x0006
06:37:46:394 ZCL configure reporting rsp seq: 11 0xB4E3F9FFFEBE922F for ep: 0x01 cluster: 0x0006 attr: 0x0000 status: 0x00
06:37:46:465 Bind response success for 0xb4e3f9fffebe922f ep: 0x01 cluster: 0x0008
06:37:46:466 skip configure report for cluster: 0x0008 attr: 0x0000 of node 0xB4E3F9FFFEBE922F (wait reading or unsupported)
06:37:49:717 Bind response success for 0xb4e3f9fffebe9477 ep: 0x01 cluster: 0x0000
06:37:49:834 ZCL configure reporting rsp seq: 14 0xB4E3F9FFFEBE9477 for ep: 0x01 cluster: 0x0000 attr: 0x4000 status: 0x00
06:38:03:919 Bind response success for 0xb4e3f9fffebe9477 ep: 0x01 cluster: 0x0006
06:38:04:025 ZCL configure reporting rsp seq: 23 0xB4E3F9FFFEBE9477 for ep: 0x01 cluster: 0x0006 attr: 0x0000 status: 0x00
06:38:04:081 Bind response success for 0xb4e3f9fffebe922f ep: 0x01 cluster: 0x0000
06:38:05:212 Bind response success for 0xb4e3f9fffebe9477 ep: 0x01 cluster: 0x0008
06:38:05:212 skip configure report for cluster: 0x0008 attr: 0x0000 of node 0xB4E3F9FFFEBE9477 (wait reading or unsupported)
06:38:05:265 Bind response success for 0xb4e3f9fffebe922f ep: 0x01 cluster: 0x0006
06:38:05:265 skip configure report for cluster: 0x0006 attr: 0x0000 of node 0xB4E3F9FFFEBE922F (seems to be active)
06:38:05:479 ZCL attribute report 0x00158D0007EE0EE1 for cluster: 0x0000, ep: 0x01, frame control: 0x1C, mfcode: 0x115F 
06:38:05:479 0x00158D0007EE0EE1 extract Xiaomi special attribute 0xFF01
06:38:05:480 	01 battery 3015 (0x0BC7)
06:38:05:480 	03 Device temperature 19 °C
06:38:05:480 	04 unknown 5032 (0x13A8)
06:38:05:480 	05 RSSI dB (?) 68 (0x0044)
06:38:05:480 	06 LQI (?) 25770131456 (0x0600050000)
06:38:05:481 	08 unknown 518 (0x0206)
06:38:05:481 	0a Parent NWK 0 (0x0000)
06:38:05:481 	64 on/off 0
06:38:11:245 Bind response success for 0xb4e3f9fffebe9477 ep: 0x01 cluster: 0x0000
06:38:16:202 Device TTL 3499 s flags: 0x7
06:38:26:047 New websocket 172.30.32.1:58184 (state: 3) 
06:38:27:256 Bind response success for 0xb4e3f9fffebe9477 ep: 0x01 cluster: 0x0006
06:38:27:256 skip configure report for cluster: 0x0006 attr: 0x0000 of node 0xB4E3F9FFFEBE9477 (seems to be active)
06:38:57:302 ZCL attribute report 0xB4E3F9FFFEBE922F for cluster: 0x0008, ep: 0x01, frame control: 0x38, mfcode: 0x0000 
06:39:16:193 Device TTL 3439 s flags: 0x7
06:39:18:743 0xb4e3f9fffebe9477 found group 0xFFF0
06:39:18:744 0xb4e3f9fffebe9477 found group 0x0001
06:39:19:438 0xb4e3f9fffebe922f found group 0xFFF0
06:39:19:438 0xb4e3f9fffebe922f found group 0x0002
06:39:20:689 remove binding from 0xB4E3F9FFFEBE922F cluster 0xFFFD due non existing cluster
06:39:20:728 Unbind response failed with status 0x88 for 0xb4e3f9fffebe922f ep: 0x01 cluster: 0xFFFD
06:40:16:195 Device TTL 3379 s flags: 0x7
06:41:16:194 Device TTL 3319 s flags: 0x7
06:41:24:233 ZCL attribute report 0xB4E3F9FFFEBE9477 for cluster: 0x0006, ep: 0x01, frame control: 0x38, mfcode: 0x0000 
06:41:28:223 ZCL attribute report 0xB4E3F9FFFEBE9477 for cluster: 0x0008, ep: 0x01, frame control: 0x38, mfcode: 0x0000 
06:41:31:162 GW firmware version is up to date: 0x26720700
06:42:16:195 Device TTL 3259 s flags: 0x7
06:43:16:194 Device TTL 3198 s flags: 0x7
06:44:02:896 ZCL attribute report 0x00158D00086523C9 for cluster: 0x0402, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
06:44:02:902 ZCL attribute report 0x00158D00086523C9 for cluster: 0x0405, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
06:44:02:911 ZCL attribute report 0x00158D00086523C9 for cluster: 0x0403, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
06:44:16:193 Device TTL 3138 s flags: 0x7
06:45:16:195 Device TTL 3078 s flags: 0x7
06:45:31:162 GW firmware version is up to date: 0x26720700
06:46:16:195 Device TTL 3017 s flags: 0x7
06:46:18:364 ZCL attribute report 0xB4E3F9FFFEBE922F for cluster: 0x0006, ep: 0x01, frame control: 0x38, mfcode: 0x0000 
06:47:16:195 Device TTL 2957 s flags: 0x7
06:48:16:194 Device TTL 2897 s flags: 0x7
06:49:16:196 Device TTL 2836 s flags: 0x7
06:49:31:162 GW firmware version is up to date: 0x26720700
06:50:16:194 Device TTL 2776 s flags: 0x7
06:51:16:194 Device TTL 2716 s flags: 0x7
06:52:16:201 Device TTL 2655 s flags: 0x7
06:53:16:194 Device TTL 2595 s flags: 0x7
06:53:31:162 GW firmware version is up to date: 0x26720700
06:54:16:194 Device TTL 2535 s flags: 0x7
06:55:16:194 Device TTL 2474 s flags: 0x7
06:55:52:119 ZCL attribute report 0x00158D0008651732 for cluster: 0x0000, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
06:56:16:192 Device TTL 2414 s flags: 0x7
06:57:16:196 Device TTL 2354 s flags: 0x7
06:57:31:163 GW firmware version is up to date: 0x26720700
127.0.0.1: new handler Process
localhost - - [21/Sep/2022 06:57:43] "GET //vnc_lite.html?scale=yes HTTP/1.1" 200 -
172.30.32.2 - - [21/Sep/2022:06:57:43 +0200] "GET /novnc/vnc_lite.html?scale=yes HTTP/1.1" 200 3342 "http://192.168.188.203:20535/api/hassio_ingress/G7BTRmYodTCvz4kY6-b1eApldKcla1T9XPZgjQaxjGQ/ingress.html" "Mozilla/5.0 (Linux; Android 12; SM-S901B Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.79 Mobile Safari/537.36 Home Assistant/2022.8.0-2624 (Android 12; SM-S901B)"
Ignoring interrupted syscall
```

### Additional information

If I play around with socket port by adding value 8081 and removing it followed by multiole restart of addon it starts to work again.

**Comment by ludeeus** [comment] 2022-10-04 17:45
Duplicate of https://github.com/home-assistant/supervisor/issues/3905

**Closed by ludeeus** 2022-10-04 17:45 UTC
