### ISSUE TITLE
File Editor doesn't work

### ISSUE THREAD

**Issue by LeoeLeoeL** [home-assistant/addons#1997] opened 2021-05-04 14:17 UTC
## The problem
When I try to open File Editor something else is shown

## Environment
Version is 5.3.0

- Add-on with the issue: File Editor
- Add-on release with the issue: 5.3.0
- Last working add-on release (if known): Probably the previous one
- Operating environment (OS/Supervised): 
- 

Versione | core-2021.4.6
-- | --
Tipo di installazione | Home Assistant OS
Sviluppo | false
Supervisor | true
Docker | true
Ambiente virtuale | false
Versione Python | 3.8.7
Famiglia del Sistema Operativo | Linux
Versione del Sistema Operativo | 5.4.109
Architettura della CPU | x86_64
Fuso orario | Europe/Rome

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

## Additional information
![image](https://user-images.githubusercontent.com/65825223/117017495-ed1c0900-acf3-11eb-8747-bb5272b5908d.png)
![image](https://user-images.githubusercontent.com/65825223/117017614-058c2380-acf4-11eb-8f3d-859fac3de3be.png)
Many many pages of that.

**Comment by LeoeLeoeL** [comment] 2021-05-04 14:33
I have AdGuard Home running in Synology docker since january 2021. Last update of Adguard Home was in middle march and File Editor worked after that.

**Comment by frenck** [comment] 2021-05-04 14:35
That sounds nice, but AdGuard updates filters regardless of its own release cycle.

Unsure if AdGuard is the cause or not, please provide browser logs on what was blocked from loading.

**Comment by LeoeLeoeL** [comment] 2021-05-04 14:35
Anyway if I deactivate AdGuard now, File Editor works.

**Comment by LeoeLeoeL** [comment] 2021-05-04 14:41
I forgot to thank you.
:-)

**Comment by LeoeLeoeL** [comment] 2021-05-04 14:49
I checked AdGuard log and everything concerning the IP of Home Assistant is processed.
The only records blocked I found were in 24/04/2024 about cloudflare.
So, AdGuard doesn't block but... blocks!

**Comment by frenck** [comment] 2021-05-04 15:03
🤷  I'm glad to hear you found the source, as this is out of our control, I'll go ahead and close the issue on our end.

**Closed by frenck** 2021-05-04 15:03 UTC
Labels: add-on: configurator
