### ISSUE TITLE
Z-Wave JS Aeotec ZWA021 Radiator Thermostat target temperature not updating

### ISSUE THREAD

**Issue by mvv588** [home-assistant/addons#2290] opened 2021-11-27 09:52 UTC
### Describe the issue you are experiencing

When the target temperature is changed by a automation or script this is applied to the device however the reported target temperature in HA does not change. This stopped working in Z-Wave JS 0.1.49, a rollback to version 0.1.48 resolves the issue.

Same behavior on three of the same devices with the same firmware, re-interviewed and healed, full host reboots, no result.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Z-Wave JS

### What is the version of the add-on?

0.1.49

### Steps to reproduce the issue

1. Call climate.set_temperature to change the target temperature on the device.
2. Check the target temperature in the Device info
...

**Comment by MartinHjelmare** [comment] 2021-11-27 10:07
Duplicate of https://github.com/home-assistant/core/issues/60368

**Closed by MartinHjelmare** 2021-11-27 10:07 UTC
