### ISSUE TITLE
File Editor addon incompatible with Firefox

### ISSUE THREAD

**Issue by bmn001** [home-assistant/addons#2128] opened 2021-07-23 19:37 UTC
## The problem

A recent upgrade of the File Editor add-on has made it incompatible with Firefox.

Attempting to open the Web UI of File Editor in Ubuntu Firefox (v90.0) results in a `401: Unauthorized` error.

Chrome does _not_ display this error.  Chrome launches the editor without incident.

## Environment

- Add-on with the issue:
File Editor
- Add-on release with the issue: 
5.3.2
- Last working add-on release (if known): 
I wish I could tell you the previous version that was working, but I didn't make note of it before the upgrade.
- Operating environment (OS/Supervised): 
Home Assistant OS 6.1/Supervisor
core-2021.7.4

## Problem-relevant configuration

I've tried deleting and reinstalling this add-on, but this behavior appears even with a fresh install.

## Traceback/Error logs

n/a

## Additional information
I've tried restarting this add-on.
I've tried uninstalling and re-installing this add-on.
I've tried deleting cookies and logging in again.
Nothing seems to make a difference.

**Comment by WahoYate** [comment] 2021-07-28 07:39
Same to me with Firefox 90.0.2 , when I tried to access to File Editor, I Have "**401: Unauthorized**"
uninstall, re-install : same issue
When I found this page to try to find some information , I tried with Chrome and it's working !

**Comment by fortinj1354** [comment] 2021-08-09 21:33
I turned off the Firefox tracking protection for my HA instance and it started working. Not sure which script it was blocking, once I got it to load once turning the blocking back on did not break it again so I can't diagnose it.

**Comment by ludeeus** [comment] 2021-08-09 21:36
Duplicate of <https://github.com/home-assistant/supervisor/issues/3021>

**Closed by ludeeus** 2021-08-09 21:36 UTC
Labels: add-on: configurator
