### ISSUE TITLE
terminal output in Homeassistant web Interface is black-on-black

### ISSUE THREAD

**Issue by michael-eder** [home-assistant/addons#2255] opened 2021-11-06 13:31 UTC
terminal output in Homeassistant web Interface is black-on-black
input and output isnot readable

typing in commands (eg. ls, exit) seems to work but nothing cane seen.

In SSH erveything works fine.

terminal output in Homeassistant web Interface is black-on-black
input and output isnot readable

typing in commands (eg. ls, exit) seems to work but nothing cane seen.

In SSH erveything works fine.

## Environment

Terminal & SSH Current version: 9.2.1 
Core Version core-2021.11.1
Supervisor Version supervisor-2021.10.8
Operating System Home Assistant OS 6.6

- Add-on with the issue:
- Add-on release with the issue: 
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): 

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by ficklma1** [comment] 2021-11-07 13:17
I’ve been having the exact same problem starting around 10.4
macOS and iOS devices seem to be most affected.  Thinking it may be Safari related?
It works in Google Chrome

**Comment by michael-eder** [comment] 2021-11-07 19:22
I can confirm this.
It works fine in chrome.

Any idea, how to fix this in safari?

**Comment by mauriziomontanaro** [comment] 2021-11-08 17:05
I also confirm. On Safari it dosn't work

**Comment by ficklma1** [comment] 2021-11-08 17:09
@frenck - Can we have someone look into why this is happening in the Terminal Addon for iOS/macOS users (safari related) ?

**Comment by frenck** [comment] 2021-11-08 17:10
You don't have to tag me for that. No appreciated.

**Comment by ficklma1** [comment] 2021-11-08 17:14
sorry about that.

**Comment by vinyli85** [comment] 2021-11-09 14:23
Disable „WebGL 2.0“ in Safari helps

**Comment by mauriziomontanaro** [comment] 2021-11-09 16:38
> Disable „WebGL 2.0“ in Safari Advanced Settings helps
> See [xtermjs/xterm.js#3357](https://github.com/xtermjs/xterm.js/issues/3357)

it works!

**Comment by ludeeus** [comment] 2021-11-10 18:47
Duplicate of https://github.com/home-assistant/addons/issues/2186

**Closed by ludeeus** 2021-11-10 18:47 UTC
Labels: add-on: ssh

**Comment by michael-eder** [comment] 2021-11-17 08:09
In my safari version 15.1 (17612.2.9.1.20) you can disable WebGL 2.0“ not in Safari Advanced Settings but in the Developer Menu (which you can switch on in Safari Advanced Settings )
