### ISSUE TITLE
Update Zwave-JS to 1.46 crashing HA heavely

### ISSUE THREAD

**Issue by canedje** [home-assistant/addons#2252] opened 2021-11-05 20:32 UTC
## The problem
Zwave-js update to 1.46 did heavely crash the system.
Even a restore of a backup is not working
Updating the VM running HA gives an error the zwave USB is not recognized anymore.
I had to run a working backup at HA and restart the NUC for getting up and running

## Environment

- Add-on with the issue: Zwave-js
- Add-on release with the issue: 1.46
- Last working add-on release (if known):  1.45
- Operating environment (OS/Supervised): 
## System Health

version | core-2021.11.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.75
arch | x86_64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4268
Installed Version | 1.16.0
Stage | running
Available Repositories | 889
Installed Repositories | 29

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | failed to load: timeout

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.6
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.8
docker_version | 20.10.8
disk_total | 48.5 GB
disk_used | 7.6 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), NGINX Home Assistant SSL proxy (3.0.2), Node-RED (10.0.1), Samba share (9.5.1), Terminal & SSH (9.2.1), Z-Wave JS (0.1.45), Samba Backup (5.0.0), ESPHome (2021.10.3), Duck DNS (1.14.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 21
views | 97
mode | storage

</details>
## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

![image](https://user-images.githubusercontent.com/23150947/140574785-585b4789-e78c-4b56-92d0-8e29b0ad4c30.png)

```txt
   manufacturer ID:     0x86
                                    product type:        0x01
                                    product ID:          0x5a
                                    supported functions: 
                                    · GetSerialApiInitData (0x02)
                                    · FUNC_ID_SERIAL_API_APPL_NODE_INFORMATION (0x03)
                                    · ApplicationCommand (0x04)
                                    · GetControllerCapabilities (0x05)
                                    · SetSerialApiTimeouts (0x06)
                                    · GetSerialApiCapabilities (0x07)
                                    · SoftReset (0x08)
                                    · UNKNOWN_FUNC_UNKNOWN_0x09 (0x09)
                                    · SetRFReceiveMode (0x10)
                                    · UNKNOWN_FUNC_SET_SLEEP_MODE (0x11)
                                    · FUNC_ID_ZW_SEND_NODE_INFORMATION (0x12)
                                    · SendData (0x13)
                                    · SendDataMulticast (0x14)
                                    · GetControllerVersion (0x15)
                                    · SendDataAbort (0x16)
                                    · FUNC_ID_ZW_R_F_POWER_LEVEL_SET (0x17)
                                    · UNKNOWN_FUNC_SEND_DATA_META (0x18)
                                    · FUNC_ID_ZW_GET_RANDOM (0x1c)
                                    · GetControllerId (0x20)
                                    · UNKNOWN_FUNC_MEMORY_GET_BYTE (0x21)
                                    · UNKNOWN_FUNC_MEMORY_PUT_BYTE (0x22)
                                    · UNKNOWN_FUNC_MEMORY_GET_BUFFER (0x23)
                                    · UNKNOWN_FUNC_MEMORY_PUT_BUFFER (0x24)
                                    · UNKNOWN_FUNC_FlashAutoProgSet (0x27)
                                    · GetNVMId (0x29)
                                    · ExtNVMReadLongBuffer (0x2a)
                                    · ExtNVMWriteLongBuffer (0x2b)
                                    · ExtNVMReadLongByte (0x2c)
                                    · ExtExtWriteLongByte (0x2d)
                                    · GetNodeProtocolInfo (0x41)
                                    · HardReset (0x42)
                                    · FUNC_ID_ZW_REPLICATION_COMMAND_COMPLETE (0x44)
                                    · FUNC_ID_ZW_REPLICATION_SEND_DATA (0x45)
                                    · AssignReturnRoute (0x46)
                                    · DeleteReturnRoute (0x47)
                                    · RequestNodeNeighborUpdate (0x48)
                                    · ApplicationUpdateRequest (0x49)
                                    · AddNodeToNetwork (0x4a)
                                    · RemoveNodeFromNetwork (0x4b)
                                    · FUNC_ID_ZW_CREATE_NEW_PRIMARY (0x4c)
                                    · FUNC_ID_ZW_CONTROLLER_CHANGE (0x4d)
                                    · FUNC_ID_ZW_SET_LEARN_MODE (0x50)
                                    · AssignSUCReturnRoute (0x51)
                                    · FUNC_ID_ZW_REQUEST_NETWORK_UPDATE (0x53)
                                    · SetSUCNodeId (0x54)
                                    · DeleteSUCReturnRoute (0x55)
                                    · GetSUCNodeId (0x56)
                                    · UNKNOWN_FUNC_SEND_SUC_ID (0x57)
                                    · FUNC_ID_ZW_EXPLORE_REQUEST_INCLUSION (0x5e)
                                    · RequestNodeInfo (0x60)
                                    · RemoveFailedNode (0x61)
                                    · IsFailedNode (0x62)
                                    · ReplaceFailedNode (0x63)
                                    · UNKNOWN_FUNC_UNKNOWN_0x66 (0x66)
                                    · UNKNOWN_FUNC_UNKNOWN_0x67 (0x67)
                                    · GetRoutingInfo (0x80)
                                    · UNKNOWN_FUNC_LOCK_ROUTE_RESPONSE (0x90)
                                    · UNKNOWN_FUNC_GET_PRIORITY_ROUTE (0x92)
                                    · UNKNOWN_FUNC_SET_PRIORITY_ROUTE (0x93)
                                    · UNKNOWN_FUNC_UNKNOWN_0x98 (0x98)
                                    · UNKNOWN_FUNC_UNKNOWN_0xB4 (0xb4)
                                    · UNKNOWN_FUNC_WATCH_DOG_ENABLE (0xb6)
                                    · UNKNOWN_FUNC_WATCH_DOG_DISABLE (0xb7)
                                    · UNKNOWN_FUNC_WATCH_DOG_KICK (0xb8)
                                    · UNKNOWN_FUNC_UNKNOWN_0xB9 (0xb9)
                                    · UNKNOWN_FUNC_RF_POWERLEVEL_GET (0xba)
                                    · UNKNOWN_FUNC_GET_LIBRARY_TYPE (0xbd)
                                    · UNKNOWN_FUNC_SEND_TEST_FRAME (0xbe)
                                    · UNKNOWN_FUNC_GET_PROTOCOL_STATUS (0xbf)
                                    · UNKNOWN_FUNC_UNKNOWN_0xD2 (0xd2)
                                    · UNKNOWN_FUNC_UNKNOWN_0xD3 (0xd3)
                                    · UNKNOWN_FUNC_UNKNOWN_0xD4 (0xd4)
                                    · undefined (0xee)
                                    · UNKNOWN_FUNC_UNKNOWN_0xEF (0xef)
2021-11-05T20:07:50.014Z CNTRLR   Performing soft reset...
2021-11-05T20:07:50.033Z CNTRLR   Waiting for the controller to reconnect...
2021-11-05T20:07:51.535Z CNTRLR   Re-opening serial port...
2021-11-05T20:08:00.554Z DRIVER   Failed to open the serial port: Error: No such file or directory, cannot open 
                                  /dev/ttyACM0
Error in driver ZWaveError: Failed to open the serial port: Error: No such file or directory, cannot open /dev/ttyACM0 (ZW0100)
    at Driver.tryOpenSerialport (/usr/src/node_modules/zwave-js/src/lib/driver/Driver.ts:874:17)
    at Driver.ensureSerialAPI (/usr/src/node_modules/zwave-js/src/lib/driver/Driver.ts:1846:4)
    at Driver.softResetInternal (/usr/src/node_modules/zwave-js/src/lib/driver/Driver.ts:1810:9)
    at Driver.initializeControllerAndNodes (/usr/src/node_modules/zwave-js/src/lib/driver/Driver.ts:959:6)
    at Immediate.<anonymous> (/usr/src/node_modules/zwave-js/src/lib/driver/Driver.ts:817:5) {
  code: 100,
  context: undefined,
  transactionSource: undefined
}
Shutting down
2021-11-05T20:08:00.562Z CNTRLR   Waiting for the Serial API to start...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by Mkay505** [comment] 2021-11-05 20:36
Same here: 

Message:
Z-Wave JS: Setup erneut versuchen

**Comment by canedje** [comment] 2021-11-05 20:44
![image](https://user-images.githubusercontent.com/23150947/140576150-69508c06-dc42-458a-8563-158e4b1fd2e9.png)
I had exactly the same error

**Comment by Mkay505** [comment] 2021-11-05 20:51
I'm not able doing a rebuild like you did.
A restore via ha backup didn't work, you said too.

Hope the version 1.47 can repair this issue...

canedje ***@***.***> schrieb am Fr., 5. Nov. 2021, 21:44:

**Comment by canedje** [comment] 2021-11-05 20:54
I only did get it running to reboot my NUC (Running Unraid with dockers and VM) first going back to an running full restore (not the partly zwave-js snapshot)

**Comment by Mkay505** [comment] 2021-11-05 21:00
Great hint. I'll try to restore a my last full backup and reboot my ECM
Server with unRAID too. Thx

canedje ***@***.***> schrieb am Fr., 5. Nov. 2021, 21:54:

**Comment by KermitOfDarkness** [comment] 2021-11-05 21:14
Same issue here. Back Up of .45 and reboot fixes the issue, but impossible to upgrade to .46.

**Comment by Mkay505** [comment] 2021-11-05 21:29
Now it's working again. But stupid of me. I reset the Zwave Stick earlier. now all my 64 devices and over 700 entities are gone ... I thought these are stored in the home assistant.

All my automations are dead. I might throw up. Damned.

Never touch a running system. Old saying, but wise.

**Comment by kpine** [comment] 2021-11-05 21:48
0.1.46 upgraded the z-wave driver. The new version will perform a "soft-reset" of the z-wave controller upon startup. This isn't compatible with all systems, because it can result in a removal and re-insertion of the USB device. The soft-reset can be disabled, but the addon does not provide that option yet.

**Comment by canedje** [comment] 2021-11-05 22:17
> Now it's working again. But stupid of me. I reset the Zwave Stick earlier. now all my 64 devices and over 700 entities are gone ... I thought these are stored in the home assistant.
> 
> All my automations are dead. I might throw up. Damned.
> 
> Never touch a running system. Old saying, but wise.

That’s my worst nightmare

**Comment by canedje** [comment] 2021-11-05 22:18
> 0.1.46 upgraded the z-wave driver. The new version will perform a "soft-reset" of the z-wave controller upon startup. This isn't compatible with all systems, because it can result in a removal and re-insertion of the USB device. The soft-reset can be disabled, but the addon does not provide that option yet.

Causing a lot of work and stress

**Comment by stephan890** [comment] 2021-11-05 22:19
I experience the same; after the soft-reset I can see the USB stick being disconnected from the virtual machine (Synology VM). If I reconnect the USB to the VM Zware-JS starts the init again and soft-resets the USB again resulting in a disconnect. Restored 0.1.45 and no issues.

**Comment by KermitOfDarkness** [comment] 2021-11-05 22:28
> I experience the same; after the soft-reset I can see the USB stick being disconnected from the virtual machine (Synology VM). If I reconnect the USB to the VM Zware-JS starts the init again and soft-resets the USB again resulting in a disconnect. Restored 0.1.45 and no issues.
Exactly the same issue :(

**Comment by hcooper** [comment] 2021-11-06 07:35
Yeah, this just screwed me over too. Same as other report - attempting to restore from backups. But from @kpine says this can't be too complex a hotfix to resolve?

**Comment by digitalit** [comment] 2021-11-06 08:50
Following

**Comment by LucasHokerberg** [comment] 2021-11-06 09:17
A few days ago I noticed the exact same behaviour. I'm running HassOS as a VM on Unraid and the USB device was constantly being disconnected. The weird part is that my Decon container running directly on Unraid (and NOT in HA) also stopped working with an error that the USB device (ConBee II) was not reachable. After several reboots of both Unraid, Docker and HassOS VM, I got it to work (both for Deconz and Z-Wave JS). I think it was the timing between mounting the USB device in Unraid and restart of the Z-Wave JS to MQTT add-on that did the trick.

Unraid version 6.9.2
Home Assistant OS version 6.6
Home Assistant Core version 2021.10.7
Z-Wave JS to MQTT version 0.28.0

**Comment by MartinHjelmare** [comment] 2021-11-06 11:56
If you can switch to the community add-on it offers an option to disable the soft-reset.

**Comment by canedje** [comment] 2021-11-06 13:31
What do you mean "switch to the community add-on"?
I do use the standard zwave-js add-on in supervisor of HA?

**Comment by cogneato** [comment] 2021-11-06 14:53
@canedje The community add-on repository has an alternative zwavejs add-on (zwavejs to mqtt) with a few extra features and the option to disable soft reset . The mqtt is optional.

**Comment by witterholt** [comment] 2021-11-06 15:02
I have the same problem. Removing and adding the stick works for some time and after that it crashed again. I restored my backup of 1.45 for now...

**Comment by canedje** [comment] 2021-11-06 15:24
@cogneato I tried that before, but did not get it up and running.
Thanks for the answer
I hope there will be a solution for the normal Zwave-JS addon

**Comment by gperreault** [comment] 2021-11-06 18:00
This also affects me (Synology VMM w/Aeotec Z-Stick Gen 5), so glad I had a snapshot to revert to.

The "Soft Reset" option found in ZWaveJS2MQTT definitely needs to be exposed in the official ZWaveJS add-on configuration.

**Comment by tiba222** [comment] 2021-11-06 18:26
Same issue here, I reverted back to 1.45 for now. I really hope this will be fixed as soon as possible.

**Comment by LucasHokerberg** [comment] 2021-11-06 20:37
I have turned off Soft Reset and I think I can confirm it's working. I have restarted Z-Wave JS to MQTT, as well as detach and attach the USB stick in Unraid, and I don't see any unexpected "Hardware Removed" in the logs. For now, it's working like a charm!

Not sure how and if this could have affect Deconz as well. Perhaps it's just one hell of a coincident, or something happens with the USB controller in Unraid.

**Comment by LasseTheDude** [comment] 2021-11-06 22:00
Same here! Had a lat of trouble. Had to rollback to .45 and restart NUC. The Z wave stick was glowing red after the update.

**Comment by Mkay505** [comment] 2021-11-07 11:28
When I´m using "zwave js" version 1.45 AND Z-wave JS to MQTT in Version 0.28.0 > same error. (Based on core-2021.10.6)  < Core 2021.10.7 and above has an issue with "SolarEdege API"... No fun these days

zwave js 1.45 and Z-wave JS to MQTT Version 0.27.0 works (Based on core 2021.10.6)

BUT 

>>>> zwave js 1.46 and Z-wave JS to MQTT Version 0.27.0 WORKS!!!

The problem isn´t zwave js 1.46 - it is the Version 0.28.0 from Z-wave JS to MQTT.

**Comment by witterholt** [comment] 2021-11-07 12:18
> When I´m using "zwave js" version 1.45 AND Z-wave JS to MQTT in Version 0.28.0 > same error. (Based on core-2021.10.6) < Core 2021.10.7 and above has an issue with "SolarEdege API"... No fun these days
> 
> zwave js 1.45 and Z-wave JS to MQTT Version 0.27.0 works (Based on core 2021.10.6)
> 
> BUT
> 
> > > > > zwave js 1.46 and Z-wave JS to MQTT Version 0.27.0 WORKS!!!
> 
> The problem isn´t zwave js 1.46 - it is the Version 0.28.0 from Z-wave JS to MQTT.

No, it's not because I don't use the "Zwave-JS to MQTT" add-on at all and it was broken since I upgraded from "Zwave-JS 1.45" to "Zwave-JS 1.46".

**Comment by kaazvaag** [comment] 2021-11-07 12:56
I have the same issue. Rolling back to version 1.45 made it work again. 
Can someone implement an option to disable the "soft reset" of the Z-wave stick?

**Comment by tuday2** [comment] 2021-11-07 13:05
Same issue and same fix (rolling back to 1.45).

**Comment by MartinHjelmare** [comment] 2021-11-07 15:58
Please refrain from posting "same issue" and similar replies without adding new information. Every new post sends a notification to all people subscribed to the issue. The appropriate way of showing that your affected by the issue is by reacting with 👍 to the top post.

Thanks!

**Comment by djjoakim** [comment] 2021-11-07 18:53
Anyone got it working by backup to 1.45 please contact me.. I tried this, and i also tried reboot the system, i run HA on Unraid VM and my z-wave does not work anymore.. All my blinds are open and all my lights are off... :( Please help!

**Comment by korylprince** [comment] 2021-11-08 03:03
If you're running your VM on libvirt (KVM) as is pretty common, you can use udev rules to automatically reattach the USB when it gets disconnected. I wrote a [small guide here](https://community.home-assistant.io/t/fix-for-zwavejs-usb-disconnects-libvirt/354362).

In theory, this is better that just disabling the soft-reset, as I assume there are good reasons for doing so or they wouldn't have added that "feature".

**Comment by kekonn** [comment] 2021-11-08 06:35
I am also on unRaid running HASSOS in a vm and downgrading to 1.45 and rebooting the vm didn't solve the issue.

**Comment by korylprince** [comment] 2021-11-08 14:34
@kekonn you might need to remove the USB passthrough and add it back.

**Comment by kekonn** [comment] 2021-11-08 15:19
I have. I also physically unplugged it, checked the vm, then added it back
in. I switched to an external zwavejs2mqtt this morning as a workaround.

Mvg,
Jonas Van der Aa
---------------------------


Op ma 8 nov. 2021 om 15:34 schreef Kory Prince ***@***.***>:

**Comment by djjoakim** [comment] 2021-11-08 19:37
> I have. I also physically unplugged it, checked the vm, then added it back in. I switched to an external zwavejs2mqtt this morning as a workaround.

You need to restart unraid for it to work, just restarting the VM won't do the trick.

**Comment by aximusnl** [comment] 2021-11-08 19:46
Strangely, when I downgrade (I can only downgrade to 1.4.0), I get immediately upgraded again automatically to 1.4.6. Auto update is turned off.
So I don’t really have a workaround (using Synology virtual machine)

**Comment by gperreault** [comment] 2021-11-08 19:49
> In theory, this is better that just disabling the soft-reset, as I assume there are good reasons for doing so or they wouldn't have added that "feature".

To be fair, ZWaveJS has implemented soft reset this knowing that a) it breaks certain configurations, but more importantly b) provides a mechanism to override this. The next version of ZWaveJS actually tries to auto detect problematic ZWave controllers to prevent the soft reset from occurring.

It’s the “official” HA ZWaveJS add-on that does not appear to have taken either point into account.

**Comment by kpine** [comment] 2021-11-08 20:10
> The next version of ZWaveJS actually tries to auto detect problematic ZWave controllers to prevent the soft reset from occurring.

This already exists in the version of node-zwave-js that that addon has upgraded to. In addition to detecting specific controllers that are known to be problematic, the driver is also supposed to remember if a soft-reset fails, and avoid it in future startups, but that isn't working as intended. If it was, at worst it would have been a one-time failure and correctable w/o changing any settings. Unfortunately, there isn't the manual fallback to workaround it.

**Comment by aximusnl** [comment] 2021-11-08 21:06
I've opened a PR that allows the user to disable the soft reset from within Home Assistant: https://github.com/home-assistant/addons/pull/2260

**Comment by MartinHjelmare** [comment] 2021-11-09 12:49
In https://github.com/home-assistant/addons/pull/2261 we've added detection of VM in use and automatic disable of soft-reset. We want to allow users to get running as easy as possible without configuring options as far as possible.

An option for advanced users, that can configure their VM and want to use soft-reset, is ok to add but it must be compatible with the automatic handling. :+1: 

Please test version 0.1.47 when it shows up and report the success/failure. Thanks!

**Comment by LasseTheDude** [comment] 2021-11-09 16:20
> In #2261 we've added detection of VM in use and automatic disable of soft-reset. We want to allow users to get running as easy as possible without configuring options as far as possible.
> 
> An option for advanced users, that can configure their VM and want to use soft-reset, is ok to add but it must be compatible with the automatic handling. 👍
> 
> Please test version 0.1.47 when it shows up and report the success/failure. Thanks!

Works perfect. But had to restart HA server after update to .47. Thank you allot 🤝

**Comment by MartinHjelmare** [comment] 2021-11-09 16:24
Closing here since 0.1.47 seems to resolve the issue. We'll continue to try improve how soft-reset is handled and welcome help with that.

**Closed by MartinHjelmare** 2021-11-09 16:24 UTC
Labels: add-on: zwave_js

**Comment by kimfrellsen** [comment] 2021-11-09 16:35
0.1.47 tested with hass 2021.11.2 on ESXi 6.7. Issue resolved.
Thank you very much for the fix!

**Comment by witterholt** [comment] 2021-11-09 16:45
0.1.47 Tested with hass 2021.11.2 on ESXi 7.0U2a. Issue resolved.

**Comment by canedje** [comment] 2021-11-09 16:46
Yes 1.27 did the trick.
Thanks!!!

**Comment by aximusnl** [comment] 2021-11-09 16:48
Yup, same here. If anyone still needs an option to turn it on or off manually, let me know.

**Comment by digitalit** [comment] 2021-11-09 17:17
Hi guys,
Maybe i'm not suppose to yet but i cant see the 0.1.47 update?

**Comment by MartinHjelmare** [comment] 2021-11-09 17:19
Try refreshing the add-on store.

**Comment by digitalit** [comment] 2021-11-09 17:50
Thank you so much guys,

I can confirm that 0.1.47 is working fine.

UnRaid 6.9.2
Hassos 6.6 VM

**Comment by kekonn** [comment] 2021-11-09 18:55
Same here, the update seems to have fixed the issue.

**Comment by Mkay505** [comment] 2021-11-09 19:23
Not working. 1.47, unRAID, USB not found :(
Message like: 
Try setup again: none

No config possible

When I try to start:
Device '/dev/serial/by-id/usb-0658_0200-if00' does not exists! in Z-Wave JS (core_zwave_js).

What did I tried:
Update the Zwave and Zwave mqtt
Rebooted the unRAID Host

**Comment by MartinHjelmare** [comment] 2021-11-09 19:35
Which add-on are you running. The fix was only done for the official zwave_js add-on. If you're running the community zwavejs2mqtt add-on you need to disable soft-reset manually in the zwavejs2mqtt settings.

**Comment by Mkay505** [comment] 2021-11-09 20:33
Thank you. It was the zwave2mqtt addon.
Great :)

Martin Hjelmare ***@***.***> schrieb am Di., 9. Nov. 2021,
20:35:

**Comment by tuday2** [comment] 2021-11-09 21:05
Thanks so much!

I can confirm that 0.1.47 is working fine.

ESXi 7.0.3
Hassos 6.6 VM

**Comment by Mkay505** [comment] 2021-11-10 10:48
Good news in front: Zwave_js module is working, but the system logs show cyclically:

21-11-10 11:29:41 ERROR (SyncWorker_3) [supervisor.docker.interface] Container addon_core_zwave_js is not running
21-11-10 11:29:57 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with core_zwave_js!

The warning is repeated every 30 seconds.
The error is repeated every 5 minutes.

21-11-10 11:44:04 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with core_zwave_js!
21-11-10 11:44:04 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_core_zwave_js application
21-11-10 11:44:04 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-zwave_js with version 0.1.47
21-11-10 11:44:05 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from core_zwave_js
21-11-10 11:44:34 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with core_zwave_js!
21-11-10 11:44:35 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_core_zwave_js application
21-11-10 11:44:35 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-zwave_js with version 0.1.47
21-11-10 11:44:35 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from core_zwave_js
21-11-10 11:44:49 ERROR (SyncWorker_0) [supervisor.docker.interface] Container addon_core_zwave_js is not running

What´s going wrong?

z-wave js 0.1.47
z-wave js 2mqtt 0.28
supervisor-2021.10.8

**Comment by MartinHjelmare** [comment] 2021-11-10 11:00
You can't run both the official add-on `core_zwave_js` and the community add-on for zwavejs2mqtt connecting to the same controller at the same time.

If you have set up the integration to use the official add-on the integration will manage the add-on and try to install and upgrade it if it detects it not running.

If you don't want to use the official add-on you need to re-configure the server in the integration configuration panel to not use the official add-on and enter the websocket URL to the community zwavejs2mqtt add-on manually.

This problem is not related to this issue, so please continue troubleshooting in our help channels if needed:
https://www.home-assistant.io/help/#communication-channels

**Comment by cdu913** [comment] 2021-11-10 13:39
Hi, 

I have the same issue like reported here (with 1.46 or 1.47), however, in a non-VM env.

## System Health (after fallback to 1.45)

version | core-2021.10.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4978
Installed Version | 1.15.2
Stage | running
Available Repositories | 900
Installed Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 24. November 2021, 01:00
relayer_connected | true
remote_enabled | false
remote_connected | false
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-1.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.6
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.8
docker_version | 20.10.8
disk_total | 13.9 GB
disk_used | 5.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.0.1), ESPHome (2021.10.3), Terminal & SSH (9.2.1), AppDaemon 4 (0.7.0), File editor (5.3.3), Z-Wave JS (0.1.45)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 1
views | 6
mode | storage

</details>

The Z-Wave JS log below (with 1.47)

021-11-10T11:49:03.522Z DRIVER   ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
                                  ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
                                    ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
                                   ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
                                  ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
                                  ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝
2021-11-10T11:49:03.531Z DRIVER   version 8.7.5
2021-11-10T11:49:03.532Z DRIVER   
2021-11-10T11:49:03.634Z CONFIG   version 8.7.5
2021-11-10T11:49:05.005Z CNTRLR   querying controller IDs...
2021-11-10T11:49:05.350Z CNTRLR   received controller IDs:
                                    home ID:     0xeb55cf3d
                                    own node ID: 1
2021-11-10T11:49:05.351Z CNTRLR   querying API capabilities...
2021-11-10T11:49:05.383Z CNTRLR   received API capabilities:
                                    serial API version:  15.1
                                    manufacturer ID:     0x0109
                                    product type:        0x1001
                                    product ID:          0x0201
                                    supported functions: 
                                    · GetSerialApiInitData (0x02)
                                    · FUNC_ID_SERIAL_API_APPL_NODE_INFORMATION (0x03)
                                    · ApplicationCommand (0x04)
                                    · GetControllerCapabilities (0x05)
                                    · SetSerialApiTimeouts (0x06)
                                    · GetSerialApiCapabilities (0x07)
                                    · SoftReset (0x08)
                                    · UNKNOWN_FUNC_UNKNOWN_0x09 (0x09)
                                    · SerialAPIStarted (0x0a)
                                    · SetRFReceiveMode (0x10)
                                    · UNKNOWN_FUNC_SET_SLEEP_MODE (0x11)
                                    · FUNC_ID_ZW_SEND_NODE_INFORMATION (0x12)
                                    · SendData (0x13)
                                    · SendDataMulticast (0x14)
                                    · GetControllerVersion (0x15)
                                    · SendDataAbort (0x16)
                                    · FUNC_ID_ZW_R_F_POWER_LEVEL_SET (0x17)
                                    · UNKNOWN_FUNC_SEND_DATA_META (0x18)
                                    · FUNC_ID_ZW_GET_RANDOM (0x1c)
                                    · GetControllerId (0x20)
                                    · UNKNOWN_FUNC_MEMORY_GET_BYTE (0x21)
                                    · UNKNOWN_FUNC_MEMORY_PUT_BYTE (0x22)
                                    · UNKNOWN_FUNC_MEMORY_GET_BUFFER (0x23)
                                    · UNKNOWN_FUNC_MEMORY_PUT_BUFFER (0x24)
                                    · UNKNOWN_FUNC_FlashAutoProgSet (0x27)
                                    · UNKNOWN_FUNC_UNKNOWN_0x28 (0x28)
                                    · GetNVMId (0x29)
                                    · ExtNVMReadLongBuffer (0x2a)
                                    · ExtNVMWriteLongBuffer (0x2b)
                                    · ExtNVMReadLongByte (0x2c)
                                    · ExtExtWriteLongByte (0x2d)
                                    · GetNodeProtocolInfo (0x41)
                                    · HardReset (0x42)
                                    · FUNC_ID_ZW_REPLICATION_COMMAND_COMPLETE (0x44)
                                    · FUNC_ID_ZW_REPLICATION_SEND_DATA (0x45)
                                    · AssignReturnRoute (0x46)
                                    · DeleteReturnRoute (0x47)
                                    · RequestNodeNeighborUpdate (0x48)
                                    · ApplicationUpdateRequest (0x49)
                                    · AddNodeToNetwork (0x4a)
                                    · RemoveNodeFromNetwork (0x4b)
                                    · FUNC_ID_ZW_CREATE_NEW_PRIMARY (0x4c)
                                    · FUNC_ID_ZW_CONTROLLER_CHANGE (0x4d)
                                    · FUNC_ID_ZW_SET_LEARN_MODE (0x50)
                                    · AssignSUCReturnRoute (0x51)
                                    · FUNC_ID_ZW_REQUEST_NETWORK_UPDATE (0x53)
                                    · SetSUCNodeId (0x54)
                                    · DeleteSUCReturnRoute (0x55)
                                    · GetSUCNodeId (0x56)
                                    · UNKNOWN_FUNC_SEND_SUC_ID (0x57)
                                    · FUNC_ID_ZW_EXPLORE_REQUEST_INCLUSION (0x5e)
                                    · RequestNodeInfo (0x60)
                                    · RemoveFailedNode (0x61)
                                    · IsFailedNode (0x62)
                                    · ReplaceFailedNode (0x63)
                                    · UNKNOWN_FUNC_UNKNOWN_0x66 (0x66)
                                    · UNKNOWN_FUNC_UNKNOWN_0x67 (0x67)
                                    · GetRoutingInfo (0x80)
                                    · UNKNOWN_FUNC_LOCK_ROUTE_RESPONSE (0x90)
                                    · UNKNOWN_FUNC_GET_PRIORITY_ROUTE (0x92)
                                    · UNKNOWN_FUNC_SET_PRIORITY_ROUTE (0x93)
                                    · UNKNOWN_FUNC_UNKNOWN_0x98 (0x98)
                                    · UNKNOWN_FUNC_UNKNOWN_0xB4 (0xb4)
                                    · UNKNOWN_FUNC_WATCH_DOG_ENABLE (0xb6)
                                    · UNKNOWN_FUNC_WATCH_DOG_DISABLE (0xb7)
                                    · UNKNOWN_FUNC_WATCH_DOG_KICK (0xb8)
                                    · UNKNOWN_FUNC_UNKNOWN_0xB9 (0xb9)
                                    · UNKNOWN_FUNC_RF_POWERLEVEL_GET (0xba)
                                    · UNKNOWN_FUNC_GET_LIBRARY_TYPE (0xbd)
                                    · UNKNOWN_FUNC_SEND_TEST_FRAME (0xbe)
                                    · UNKNOWN_FUNC_GET_PROTOCOL_STATUS (0xbf)
                                    · UNKNOWN_FUNC_UNKNOWN_0xD2 (0xd2)
                                    · UNKNOWN_FUNC_UNKNOWN_0xD3 (0xd3)
                                    · UNKNOWN_FUNC_UNKNOWN_0xD4 (0xd4)
                                    · undefined (0xee)
                                    · UNKNOWN_FUNC_UNKNOWN_0xEF (0xef)
2021-11-10T11:49:05.391Z CNTRLR   Performing soft reset...
2021-11-10T11:49:05.414Z CNTRLR   Waiting for the controller to reconnect...
2021-11-10T11:49:06.919Z CNTRLR   Waiting for the Serial API to start...

Should I open an new issue ?

**Comment by MartinHjelmare** [comment] 2021-11-10 19:44
What's the problem symptom? I don't see any error in the log.

**Comment by cdu913** [comment] 2021-11-10 20:27
sorry, below the missing lines. It goes in a loop and I looe my z-wave devices.
It actually seems to be a different issue with 1.47 in my case

2021-11-10T20:17:17.633Z CNTRLR   Did not receive notification that Serial API has started, checking if it respo
                                  nds...
2021-11-10T20:17:17.659Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-11-10T20:17:17.765Z CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                                  n 1100 ms.
2021-11-10T20:17:18.885Z CNTRLR   Serial API did not respond, trying again in 2 seconds...
[21:17:19] INFO: Successfully send discovery information to Home Assistant.
2021-11-10T20:17:22.002Z DRIVER   ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
                                  ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
                                    ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
                                   ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
                                  ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
                                  ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝
2021-11-10T20:17:22.012Z DRIVER   version 8.7.5
2021-11-10T20:17:22.013Z DRIVER   
2021-11-10T20:17:22.122Z CONFIG   version 8.7.5

**Comment by cdu913** [comment] 2021-11-10 20:44
mit 1.45
![image](https://user-images.githubusercontent.com/77567011/141190431-aafe19bd-55d8-481e-ae87-c2a736e7ba45.png)

mit 1.47
![image](https://user-images.githubusercontent.com/77567011/141190503-a9a886d4-889a-496c-88c4-8b5728f9a033.png)

**Comment by MartinHjelmare** [comment] 2021-11-11 00:36
@cdu913 please open a new issue in our core repo. It's not clear that your problem has the same cause as this issue.

Please be sure to include the full driver debug level log in the issue.

Thanks!
