### ISSUE TITLE
SambaShare doesn't check eth0 port.

### ISSUE THREAD

**Issue by Pansovi4** [home-assistant/addons#2468] opened 2022-05-03 11:57 UTC
### Describe the issue you are experiencing

Hello,

I am trying to start SambaShare addon on Hassio supervised.
After start - i get an error that there is no connection on wlan0 port.

However my rasppi4 connected through eth0.

I added in configuration:
interfaces: eth0

Still the same - addon starts and check only wlan0.

Configuration:

username: homeassistant
password: homeassistant
workgroup: WORKGROUP
compatibility_mode: false
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - fe80::/10
interfaces: eth0

Raspberry has IP: 192.168.0.184

Log file: 

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] samba.sh: executing... 
[14:45:36] INFO: Hostname: raspberrypi
[14:45:36] INFO: Interfaces: wlan0 
No builtin backend found, trying to load plugin
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
account_policy_get: tdb_fetch_uint32_t failed for type 1 (min password length), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 2 (password history), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 3 (user must logon to change password), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 4 (maximum password age), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 5 (minimum password age), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 6 (lockout duration), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 7 (reset count minutes), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 8 (bad lockout attempt), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 9 (disconnect time), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 10 (refuse machine password change), returning 0
Added user homeassistant.
[cont-init.d] samba.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
nmbd version 4.13.17 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
Registered MSG_REQ_POOL_USAGE
smbd version 4.13.17 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
Processing section "[config]"
Processing section "[addons]"
Processing section "[ssl]"
Processing section "[share]"
Processing section "[backup]"
Processing section "[media]"
interpret_interface: Can't find address for wlan0
WARNING: no network interfaces found
daemon_status: daemon 'nmbd' : No local IPv4 non-loopback interfaces available, waiting for interface ...
NOTE: NetBIOS name resolution is not supported for Internet Protocol Version 6 (IPv6).
interpret_interface: Can't find address for wlan0
WARNING: no network interfaces found
INFO: Profiling support unavailable in this build.
Registered MSG_REQ_POOL_USAGE
No builtin backend found, trying to load plugin
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_POOL_USAGE
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
open_sockets_smbd: No sockets available to bind to.
===============================================================
INTERNAL ERROR: open_sockets_smbd() failed in pid 285 (4.13.17)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 285): open_sockets_smbd() failed in 4.13.17
unable to produce a stack trace on this platform
dumping core in /var/log/samba/cores/smbd
smbd version 4.13.17 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
Processing section "[config]"
Processing section "[addons]"
Processing section "[ssl]"
Processing section "[share]"
Processing section "[backup]"
Processing section "[media]"
interpret_interface: Can't find address for wlan0
WARNING: no network interfaces found
INFO: Profiling support unavailable in this build.
Registered MSG_REQ_POOL_USAGE
No builtin backend found, trying to load plugin
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_POOL_USAGE
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
open_sockets_smbd: No sockets available to bind to.
===============================================================
INTERNAL ERROR: open_sockets_smbd() failed in pid 310 (4.13.17)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 310): open_sockets_smbd() failed in 4.13.17
unable to produce a stack trace on this platform
dumping core in /var/log/samba/cores/smbd
smbd version 4.13.17 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
Processing section "[config]"
Processing section "[addons]"
Processing section "[ssl]"
Processing section "[share]"
Processing section "[backup]"
Processing section "[media]"

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Samba share

### What is the version of the add-on?

9.6.1

### Steps to reproduce the issue

1. restart add-on
2. added *interfaces = eth0*
3. reinstalled add-on
...

### Anything in the add-on logs that might be useful for us?

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] samba.sh: executing... 
[14:45:36] INFO: Hostname: raspberrypi
[14:45:36] INFO: Interfaces: wlan0 
No builtin backend found, trying to load plugin
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
account_policy_get: tdb_fetch_uint32_t failed for type 1 (min password length), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 2 (password history), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 3 (user must logon to change password), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 4 (maximum password age), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 5 (minimum password age), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 6 (lockout duration), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 7 (reset count minutes), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 8 (bad lockout attempt), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 9 (disconnect time), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 10 (refuse machine password change), returning 0
Added user homeassistant.
[cont-init.d] samba.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
nmbd version 4.13.17 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
Registered MSG_REQ_POOL_USAGE
smbd version 4.13.17 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
Processing section "[config]"
Processing section "[addons]"
Processing section "[ssl]"
Processing section "[share]"
Processing section "[backup]"
Processing section "[media]"
interpret_interface: Can't find address for wlan0
WARNING: no network interfaces found
daemon_status: daemon 'nmbd' : No local IPv4 non-loopback interfaces available, waiting for interface ...
NOTE: NetBIOS name resolution is not supported for Internet Protocol Version 6 (IPv6).
interpret_interface: Can't find address for wlan0
WARNING: no network interfaces found
INFO: Profiling support unavailable in this build.
Registered MSG_REQ_POOL_USAGE
No builtin backend found, trying to load plugin
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_POOL_USAGE
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
open_sockets_smbd: No sockets available to bind to.
===============================================================
INTERNAL ERROR: open_sockets_smbd() failed in pid 285 (4.13.17)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 285): open_sockets_smbd() failed in 4.13.17
unable to produce a stack trace on this platform
dumping core in /var/log/samba/cores/smbd
smbd version 4.13.17 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
Processing section "[config]"
Processing section "[addons]"
Processing section "[ssl]"
Processing section "[share]"
Processing section "[backup]"
Processing section "[media]"
interpret_interface: Can't find address for wlan0
WARNING: no network interfaces found
INFO: Profiling support unavailable in this build.
Registered MSG_REQ_POOL_USAGE
No builtin backend found, trying to load plugin
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_POOL_USAGE
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
open_sockets_smbd: No sockets available to bind to.
===============================================================
INTERNAL ERROR: open_sockets_smbd() failed in pid 310 (4.13.17)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 310): open_sockets_smbd() failed in 4.13.17
unable to produce a stack trace on this platform
dumping core in /var/log/samba/cores/smbd
smbd version 4.13.17 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
Processing section "[config]"
Processing section "[addons]"
Processing section "[ssl]"
Processing section "[share]"
Processing section "[backup]"
Processing section "[media]"
```

**Comment by pvizeli** [comment] 2022-05-03 13:25
Can you report the `ha info` and `ha host info` to verify it run on a supported system?

**Comment by mdegat01** [comment] 2022-05-03 15:29
> added interfaces = eth0

The `interfaces` configuration option doesn't exist in the addon anymore. The addon simply binds to all interfaces supported by supervisor. Since you are trying to run the addon in an unsupported supervised setup most likely you have no interfaces managed and supported by supervisor so this addon won't work for you.

See #2447 for more information. Believe there is also a fork you can try. Although would highly recommend switching to a supported system as then this addon works fine.

Duplicate of #2447

**Closed by mdegat01** 2022-05-03 15:29 UTC
Labels: unsupported
